### ISSUE TITLE
Implement Webpack DLL plugin for faster builds

### ISSUE THREAD

**Issue by tirthbodawala** [Atyantik/react-pwa#10]

**Comment by jhabdas** [comment]
Just spotted this issue and it raised an eyebrow. Would it be more astute to eat the pain rather than getting so low-level? I've made the suggestion in the past [Webpack is an Achilles‘ Heel](https://medium.com/@jhabdas/webpack-is-your-achilles-heel-d3cd80821a4f).

**Comment by dav-is** [comment]
@jhabdas it seems your argument is that using Webpack is bad because of how long it takes to get it set up? Well in this case it’s built already and it adds several features already. There’s no need to put more time to try and get the same features in rollup.

**Comment by tirthbodawala** [comment]
Hello @dav-is & @jhabdas I really appreciate the discussion. I stumbled upon a discussion here @ https://stackoverflow.com/questions/43219030/what-is-flat-bundling-and-why-is-rollup-better-at-this-than-webpack 
The DLL is not a go yet, and I am open to switch bundling if its worth it. Just need few reviews and explanations. 

Your inputs are always invaluable. Thanks again.

**Comment by dav-is** [comment]
The point made in one of those responses that I agre with fully is that rollup is better for libraries while Webpack is better for apps.

**Comment by jhabdas** [comment]
Sorry if linking to my post muddled my intention. Idea is to not use a DLL to improve the speed of webpack, but instead to let Webpack be slow so other options are more enticing. As @tirthbodawala points out this feature is not yet implemented.

WRT using one tool over another Rich Harris, dude who created Rollup, suggests using rollup for libs and webpack for apps as @dav-is suggested (lmk if you'd like the resource). The reason I'm against Webpack is more for keeping things simple whenever possible. 😅

**Comment by tirthbodawala** [comment]
Thanks @jhabdas. 
So you mean its better not to use DLL plugin at all and let it stay as it is, cause it gives more functionality and flexibility ? 
Also do you have better solution for our problems of code-splitting and SSR, Instead of webpack? if yes I am reading your replies :) 

At the end, what I want is a great framework for everyone with speed and usability. Don't want to slow down anyone. 

Thanks guys for your Contributions.

**Comment by jhabdas** [comment]
I've lost a little bit of my pulse on the react space recently, but if I run across something I'll be sure to mention it. The reason I lifted the eyebrow was more because I saw the term `DLL` (which I associate with Windows-only) and less about optimizing performance. If it feels good do it. You've already done such an awesome job on this piece of work deck it out. You can always pull stuff later. Sorry for deliberating without a more complete picture—it's the [ENTP](https://www.16personalities.com/entp-personality) talking more than anything else.

Love love love this kit. Can you do a [Marko one](https://hackernoon.com/server-side-rendering-shootout-with-marko-preact-rax-react-and-vue-25e1ae17800f) next? 😺

**Comment by tirthbodawala** [comment]
@jhabdas Sure ill give it a try. Also we are writing a docs site for this boilerplate. 
https://www.reactpwa.com. Do share your inputs. they are very valuable :)

**Comment by jhabdas** [comment]
Just a couple of quick feedback items. You'll probably get some pretty good mileage creating a docs site using the following GH-pages compatible template (which includes a search feature):

Also, to sell the pill here are two resources which may help, one is mine:
https://julian.is/article/progressive-web-apps/
https://habd.as/telltale-signs-your-react-app-isnt-seo-friendly/

If you can make even a half-assed logo or mascot you'll see more rapid adoption.

**Comment by tirthbodawala** [comment]
That is very very helpful @jhabdas. Noted everything and going in the direction mentioned. Thanks again for your valuable time.

**Comment by tirthbodawala** [comment]
@jhabdas We have dropped the idea to upgrade to webpack-dll. It not necessary as of now, shall re-open the issue if demanded by many others. 

Thanks @jhabdas and @dav-is for your inputs.
