### ISSUE TITLE
'Add to home screen'  doesn't popup

### ISSUE THREAD

**Issue by YasiruDev** [Atyantik/react-pwa#104]
i tried pwajs in my project and visit my page more than 3 times withing 5 mins.but it's won't popup

**Comment by tirthbodawala** [comment]
Hey @YasiruDev you tried PawJS in you project, but how? Can you please share the following details?
`package.json`
`pawconfig.json` 

Device details: 
 - OS
 - Hardare Configuration
 - Browser you are using

**Comment by LeonardoManzella** [comment]
Hi @YasiruDev 
I am currently experiencing the same issue. with the master repository version using the default config.

When I access to https://demo.reactpwa.com in my smartphone it works fine, but it doesn't work when running locally (on my netbook) and browsing to `netbook_ip:port` from my smartphone  


This is my package.json:

> {
>   "name": "react-pwa",
>   "version": "2.2.3",
>   "description": "A highly scalable, Progressive Web Application foundation with the best Developer Experience (DX).",
>   "scripts": {
>     "start": "pawjs --no-cache --env=development start",
>     "build": "pawjs --no-cache --config=./prod-pawconfig.json --env=production build",
>     "build:demo": "pawjs --no-cache --config=./demo-pawconfig.json --env=production build",
>     "lint": "pawjs lint",
>     "test": "pawjs --no-cache test",
>     "snyk-protect": "snyk protect",
>     "prepare": "npm run snyk-protect"
>   },
>   "author": {
>     "name": "Atyantik Technologies",
>     "email": "admin@atyantik.com",
>     "url": "https://www.atyantik.com/"
>   },
>   "contributors": [
>     {
>       "name": "Tirth Bodawala",
>       "email": "tirthbodawala@atyantik.com",
>       "url": "https://www.atyantik.com/"
>     },
>     {
>       "name": "Yash Thakur",
>       "email": "thakur.yash514@gmail.com",
>       "url": "http://yashthakur.in/"
>     },
>     {
>       "name": "Ajay Patel",
>       "email": "ajaypatel@atyantik.com",
>       "url": "https://www.atyantik.com/"
>     }
>   ],
>   "license": "MIT",
>   "dependencies": {
>     "@pawjs/image-optimizer": "^2.2.0-beta.0",
>     "@pawjs/pawjs": "^2.3.0",
>     "@pawjs/sass": "^2.2.0-beta.0",
>     "@pawjs/srcset": "^2.1.0-beta.0",
>     "@types/react": "^16.8.1",
>     "@types/react-dom": "^16.0.11",
>     "bulma": "^0.7.2",
>     "cloudinary": "^1.13.2",
>     "eslint-import-resolver-webpack": "^0.11.0",
>     "fork-ts-checker-webpack-plugin": "^0.5.2",
>     "prop-types": "^15.6.2",
>     "react-router-config": "^4.4.0-beta.6",
>     "react-router-dom": "^4.3.1",
>     "snyk": "^1.124.1",
>     "universal-fetch": "^1.0.0"
>   },
>   "snyk": true,
>   "devDependencies": {
>     "webpack-bundle-analyzer": "^3.0.3"
>   }
> }


This is my pawconfig.json:

> {
>   "port": "3003",
>   "host": "0.0.0.0",
>   "appRootUrl": "/",
>   "asyncCSS": true,
>   "serviceWorker": false,
>   "serverSideRender": true,
>   "singlePageApplication": false
> }

**OS:** Ubuntu 18.04.1 LTS
**Hardare Configuration:** Motorola G5 Plus Android 7.0
**Browser:** Chrome 71.0.3578 (Android)
