### ISSUE TITLE
your src folder is empty

### ISSUE THREAD

**Issue by ashmitaggarwal** [Atyantik/react-pwa#105]

**Comment by tirthbodawala** [comment]
@ashmitaggarwal `src` already has 4 files
`client.js`
`server.js`
`routes.js`
`webpack.js`

Can you please let me know which src folder are you talking about?

**Comment by ashmitaggarwal** [comment]
just 4 files.. even those are empty.. nothing in there.. https://demo.reactpwa.com/ where to see the socurce code for this boilerplate

**Comment by tirthbodawala** [comment]
@ashmitaggarwal yes the repository is served with bare-minimum. For starters, you can  look at the code of [https://github.com/Atyantik/pawjs/tree/master/demo](https://github.com/Atyantik/pawjs/tree/master/demo)

The exact code of demo.reactpwa.com was replaced and we would be adding more examples to react-pwa repo in future. Thanks for understanding.

Your contribution is appreciated.

**Comment by tirthbodawala** [comment]
@ashmitaggarwal Also one of the core developer @yash-thakur has implemented his Portfolio site using react-pwa.
Find the code below:
https://github.com/yash-thakur/pawjs-portfolio

Live Website:
https://www.yashthakur.in

Hope the above comments help
