### ISSUE TITLE
How to change title & use react.semantic-ui?

### ISSUE THREAD

**Issue by akhmadodi** [Atyantik/react-pwa#106]
I'm sorry, I'm still a beginner, sorry if my question isn't useful to you. I want to ask, how do I change the title page? is there a clear enough example to make a new route consisting of components, reducers and so on? if I use react.semantic-ui, when calling it in a component is always considered an error, is there a correct way to call it?

**Comment by yash-thakur** [comment]
@akhmadodi & @akashpayneSRO [PawJS with Semantic-UI](https://github.com/yash-thakur/pawjs-sematic-ui)

Here I have implemented the Title, Redux, and the semantic-ui.

If you have any doubts you are most welcome :)
