### ISSUE TITLE
Do I need next.js for server side rendering when using react-pwa?

### ISSUE THREAD

**Issue by zwl1619** [Atyantik/react-pwa#109]
Do I need  to install next.js for server side rendering when using react-pwa?

**Comment by tirthbodawala** [comment]
@zwl1619 Well that is interested, I have never tried it integrating with next.js but we have our own Server Side Rendering, are you facing any issues with that?

**Comment by yash-thakur** [comment]
No you do not need next.js for Server side rendering. It is inbuilt and can be turned **on** and **off** using the [configuration](https://www.reactpwa.com/docs/en/configuration.html) file.
