### ISSUE TITLE
Serve custom files (#74)

### ISSUE THREAD

**Issue by jld3103** [Atyantik/react-pwa#111]
In #74 @ThunderBoltEngineer tried to use FCM. It didn't worked out of the box because FCM trys to register a service worker under /firebase-messaging-sw.js
My point is that it's not possible to serve a custom file.
Maybe someone could make a respond to this and make a PR or I'll do it in the future.
(I think the PR should be for pwajs)

@Atyantik thanks for your great project.

**Comment by yash-thakur** [comment]
@jld3103 We can serve custom files by making a folder named "public" inside the src folder. 
This will place all the files as public in the root directory.

**Comment by jld3103** [comment]
Where is the documentation for that?
Think there was no documentation for that, but good to know this feature.

**Comment by jld3103** [comment]
Thanks!
It worked!

**Comment by tirthbodawala** [comment]
@jld3103 Apologies we still need to document it. The project has become big and needs time for documentation. Any help is appreciated.
