### ISSUE TITLE
Refused to execute script because its MIME type ('text/html') is not executable

### ISSUE THREAD

**Issue by kael** [Atyantik/react-pwa#112]
Trying to run the code out of the box with `npm start` fails, the `<body>`of the page is not displayed.

Using Linux Chrome 70 and Android Chrome Canary 72, the following error message is displayed in the console:

`Refused to execute script from 'https://[hostname]/js/[hash].js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled`.

Firefox displays:

`Loading failed for the <script> with source “https://hostname]/js/[hash].js”.`

```bash
@pawjs/pawjs ^2.1.10
Node v10.12.0
NPM 6.4.1
```

**Comment by tirthbodawala** [comment]
@kael is it dev environment or production. I want to know if this happens when you run `npm start` or `npm run build && node dist/server.js` ?

Thanks

**Comment by tirthbodawala** [comment]
@kael I tested both `npm start` and `npm build` and everything is working as expected. Please re-open the issue with more details.

**Comment by tirthbodawala** [comment]
@kael can you please upgrade to @pawjs/pawjs ^2.2.4 and try again?
