### ISSUE TITLE
Document root-level component options

### ISSUE THREAD

**Issue by ev-dev** [Atyantik/react-pwa#115]
Is there a simple way to inject root-level (parent of react-router) providers generally? Needed for all sorts of use cases like apollo client, react context, etc.

If so I'd be happy to help document this, I just began digging into the Client class hoping to find some way to do this.

**Comment by tirthbodawala** [comment]
Thanks, @ev-dev.

Well, you can add root component as you can with any react-router-config so with react-pwa you can do the below in `src/routes.js`
```javascript

import GuestRoutes from './pages/guest';
import AuthRoutes from './pages/auth';
import SplashScreen from './pages/splash';
import RootComponent from './components/root';

export default class Routes {
  // eslint-disable-next-line
  apply(routeHandler) {
    routeHandler.setPwaSchema({
      name: 'ReactPWA',
      short_name: 'ReactPWA',
    });
    routeHandler.setDefaultSeoSchema({
      title: 'ReactPWA',
    });

    const subRoutes = [
      ...GuestRoutes,
      ...AuthRoutes,
      ...SplashScreen,
    ];

    routeHandler.hooks.initRoutes.tapPromise('AppRoutes', async () => {
      routeHandler.addRoutes([
        {
          component: RootComponent,
          routes: subRoutes
        }
      ]);
    });
  }
}

```

I have not tested the above. Can you please check if the above works as expected?

**Comment by tirthbodawala** [comment]
@ev-dev sorry for the really late reply:
You might want to check our plugin @pawjs/redux
https://github.com/Atyantik/pawjs/blob/master/packages/pawjs-redux/src/server.js
https://github.com/Atyantik/pawjs/blob/master/packages/pawjs-redux/src/client.js

We have added the redux provider at the root level, you can also access the hooks in a similar manner in your custom project.
