### ISSUE TITLE
Environment Variable Support similar to React

### ISSUE THREAD

**Issue by kumarsandeep91** [Atyantik/react-pwa#117]
Is there a way to declare environment variables without installing `dotenv` npm package.
**React** did this in a very nice fashion by declaring env variables in `.env.local` and `.env.production` file.

**Comment by tirthbodawala** [comment]
Well, we do have pawconfig.json for what is the specific use case you are looking at?

**Comment by nodeEnthu** [comment]
to chime in .. I have similar issue where I want to load `port + host name` dependent on an environment I am in.  Feels like I am missing something  that is possibly already present

**Comment by yash-thakur** [comment]
@nodeEnthu As per my knowledge your case matches with the one heroku uses. Heroku uses dynamic port for the node app and if static port is provided your app wont work. For that use case we had modified our code to take the port from the environment first but if it is not provided then use the port mentioned by the user in the config file.

Here is a [link](https://www.reactpwa.com/docs/en/deploying-to-heroku.html) demonstrating how to deploy your app to Heroku.

**Comment by kumarsandeep91** [comment]
> Well, we do have pawconfig.json for what is the specific use case you are looking at?

lets say i have a api endpoint **https://api.renthobo.com/prod/xxxx** for production and  **https://localhost:3002/test/xxxx** for local and i wanted to use these endpoint with respect to environment i.e local, staging and production. in code i wanted to do something like this `let endpoint = process.env.API_END_POINT`

**Comment by ldevalbray** [comment]
I agree, this would be useful for me as well ! :)

**Comment by tirthbodawala** [comment]
@kumarsandeep91  & @kumarsandeep91 I shall create a blog or example for you. Apologies for the delay.

**Comment by kumarsandeep91** [comment]
@tirthbodawala That would be great :+1:

**Comment by nodeEnthu** [comment]
@tirthbodawala  could you please provide an example .. thanks for your time

**Comment by kumarsandeep91** [comment]
Hey any update on this one ? kindly give some time to this cause.
