### ISSUE TITLE
Adding support for api routes

### ISSUE THREAD

**Issue by nodeEnthu** [Atyantik/react-pwa#118]
Hello react-pwa team ... thanks for your hard work creating this repo:

I realize that you could make a fetch call inside the pages dir by adding a fetch call like `        fetch('https://www.atyantik.com/wp-json/wp/v2/posts/?per_page=4&_fields[]=title&_fields[]=excerpt&_fields[]=jetpack_featured_media_url')
` .. however that is a third party api. 

I have two following questions:
1) I might be missing a point here but is there a way to add api routes and backend logic to this repository.  It seems like not supported  since you have same RouteHandler for client and server.js. If it is not supported what is the recommended way of adding api?

2) How can I use a config variable lets say inside guest.js and reference  vars  like const `apiHostUrl = process.env.npm_package_config_apiBaseUrl;` So that I could make calls like         fetch(`${apiHostUrl}wp-json/wp/v2/posts/?per_page=4&_fields[]=title&_fields[]=excerpt&_fields[]=jetpack_featured_media_url`)

**Comment by yash-thakur** [comment]
Hello @nodeEnthu, you can have a look at this [repository](https://github.com/yash-thakur/airbeds) as to how internal api's are made.

**Comment by nodeEnthu** [comment]
thanks

**Comment by nodeEnthu** [comment]
for my second question... is there a way to refer variables  inside the config file (pawconfig.json)  in the code .. depending upon which env it is..

**Comment by yash-thakur** [comment]
@nodeEnthu I am not clear about your question completely.

But if you want to use different config for development and the other one for production. For Eg: SSR during development is not needed, in that case you can use it in a way mentioned in the examples. In examples we are using separate config file for production.

Repository: [Example PawJS AntDesign](https://github.com/Atyantik/example-pawjs-ant-design)
[package.json](https://github.com/Atyantik/example-pawjs-ant-design/blob/master/package.json) showing how it can be used. You can see here that there are two different configs pawconfig.json( for development) and  prod.pawconfig.json(for production).
