### ISSUE TITLE
Using sass files

### ISSUE THREAD

**Issue by ldevalbray** [Atyantik/react-pwa#121]
In the documentation, you don't specify how to use the sass middleware. 
I followed those steps : https://www.reactpwa.com/docs/en/plugin-sass.html
But importing the .scss files like a normal .css file does not work. Any idea ?

**Comment by tirthbodawala** [comment]
@ldevalbray you might want to check the file https://github.com/Atyantik/react-pwa/blob/master/src/client.js
It shows you need to import sass inside client.js or if the sass is component specific you can include it inside a particular component, just like normal css. Example:

```javascript
import React from 'react';
import styles from './local-styles.css';

export default () => (
  <h1 className={styles["title"]} >This is a title</h1>
);
```

Hope that answers your question

**Comment by ldevalbray** [comment]
I tried this way, but I get this error : "“You may need an appropriate loader to handle this file type”. Even when I followed your steps when adding the sass plugin
