### ISSUE TITLE
Compress the files with gzip

### ISSUE THREAD

**Issue by ldevalbray** [Atyantik/react-pwa#122]
I see that the files are not compressed with gzip by react-pwa webpack config. Would adding it be possible with ssr ? Moreover, is there a way to edit webpack config without editing react-pwa files in node-modules directly ? (I saw there is the webpack.js file but it seems that only adding new modules is possible)

**Comment by tirthbodawala** [comment]
Hey, @ldevalbray there are hooks for extending the WebPack config. You might want to check the plugin https://github.com/Atyantik/pawjs/tree/master/packages/pawjs-sass to see extending of webpack plugin. It will allow you to modify webpack as per your needs.

**Comment by tirthbodawala** [comment]
Well, we did add the compression in the previous version, but then decided to leave it to user configuration. The issue we faced was double gzipping encryption, one from the expressjs server and another from the nginx server. We decided to remove the default gzip compression from the server and leave it to the user to handle it. 
But I guess we can definitely have a plugin that can be added by the user if he needs compression. Let me know if that is something you might look forward to: @ldevalbray

**Comment by ldevalbray** [comment]
Yes this is exactly what I would be looking for ! 
When you say "leave it to user configuration", what do you mean, exactly ? Where are the configurations supposed to take place ? In webpack.js ? Or directly in react pwa files (in node modules). I guess, more documentations about this would be useful as well
