### ISSUE TITLE
What if I would like to apply some customizations on webpack.config.json

### ISSUE THREAD

**Issue by sinner** [Atyantik/react-pwa#129]
I would like to apply some customizations on webpack.config.json such as defining aliases to some specific directories and other things. It would be fine to have a section in the documentation explaining how to do that.

**Comment by tirthbodawala** [comment]
@sinner  & @Nedja995 I understand your concern, this can be done via hooks, I will write a doc for it soon.
Again, apologies for late reply.

**Comment by hobadams** [comment]
Hey @tirthbodawala are these docs now ready? Thanks

**Comment by ericp96** [comment]
I played around with this for a bit and it seems like you can do it from the webpack.js file with object mutation:

```js
import path from 'path';

export default class ProjectWebpack {
  apply(webpackHandler) {
     webpackHandler.hooks.beforeConfig.tap('RegisterAliases', (env, type, config) => {
       if (type === 'web') {
         config = Array.isArray(config) ? config : [config];
         config[0].resolve.alias = {
           ...config[0].resolve.alias,
           "~": path.join(process.cwd(), "src")
         };
       }
     })
  }
}
```

If you want to know what the config looks like, you can check out the [web.config.ts file](https://github.com/Atyantik/pawjs/blob/ac7e911ec4c565a6d1b8ca1062d2d08930c3ea3f/src/webpack/web.config.ts)
