### ISSUE TITLE
Documentation to add other kind of deployment process

### ISSUE THREAD

**Issue by sinner** [Atyantik/react-pwa#131]
Some of the processes we use to deploy React.js applications is building the application and after that load the build to Amazon S3 and serve it as a static site. There is no documentation nor a command to only build the application using all the great feature you have but we are not going to use (SSR, SEO...).

**Comment by tirthbodawala** [comment]
@sinner Sorry for the really late reply./ The pawconfig.js has an option to build it as a static site

```JSON
{
  'singlePageApplication': true
}
```

This will generate a static site that is deployable to any other platform as S3
