### ISSUE TITLE
how to integrate react-intl 

### ISSUE THREAD

**Issue by patelmayankce** [Atyantik/react-pwa#137]
How to add [react-intl](https://github.com/yahoo/react-intl) or any other third party react plugins in current setup?

**Comment by henryqrm** [comment]
and be SEO friendly

**Comment by oongniel** [comment]
check out:
https://github.com/Atyantik/hn-reactpwa/blob/master/src/server.js
https://github.com/Atyantik/hn-reactpwa/blob/master/src/client.js

I have wrapped AppShell around the application, that should be the ideal way of doing it.
