### ISSUE TITLE
Run app over https

### ISSUE THREAD

**Issue by DanielKwasniewski95** [Atyantik/react-pwa#138]
Hello,

I want to run application written in reactPWA with use https. I don't know how to do this, beacuse I got this application from diffrent person and also I don't have knowledge in reactPWA. I have only skills in js and basic node.js. Is there enybody who can help me and give me 
detailed instruction about using https in reactPWA.

**Comment by tirthbodawala** [comment]
Hello @DanielKwasniewski95,
We can assist you with any problems you are facing please join our gitter channel
[https://gitter.im/react-pwa/Lobby](https://gitter.im/react-pwa/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

Also running app over https requires simple configuration with nginx or any other web server.
applications like:
https://www.eventerprise.com
https://renthobo.com
https://demo.reactpwa.com
https://hn.reactpwa.com

are all supporting https protocol. You can also have a look at their repo. I can share the nginx config if you need but you can get most out of it from [this article https://hackernoon.com/configuring-your-server-to-provide-https-using-lets-encrypt-and-nginx-e46a5ae93e41](https://hackernoon.com/configuring-your-server-to-provide-https-using-lets-encrypt-and-nginx-e46a5ae93e41)
