### ISSUE TITLE
Firebase Hosting and Functions Support

### ISSUE THREAD

**Issue by dav-is** [Atyantik/react-pwa#14]
Should be made to be relatively easy to deploy on Firebase without weighing down the overall boilerplate.

What needs to be done

- [ ] server.js needs to output **ssr only** and should not serve assets whatsoever (this can be a build parameter) this can be useful outside of Firebase if using a CDN
- [ ] server.js should return express app, but shouldn't be listening (this can be changed by developer and doesn't need any changes in repo, right?)
- [ ] all public facing files should be in a single directory (service worker isn't in there?)

**Comment by tirthbodawala** [comment]
@dav-is I was going to create a task for creating deployable docker image. That should do for most of the deployments now. Docker image + docker swarm + CI = high scalability and easy of deployments. What do you say? Does firebase have support for Docker Images?

**Comment by dav-is** [comment]
I would compare [Firebase](firebase.google.com) more to `now`. The application isn't made aware of that sort of infrastructure. I've used docker in the past and like it quite a bit. I'd say support both as it's just a few extra config files and shouldn't bloat the bundles (I'm pretty sure this is how firebase works but I'm still researching).

**Comment by dav-is** [comment]
Can you help me with this @tirthbodawala ?

**Comment by tirthbodawala** [comment]
Sure. Let me dive into it. I was thinking of creating a plugin like `pawjs-firebase` to integrate with it. does that make sense?

**Comment by dav-is** [comment]
Sounds great!

**Comment by bytewiz** [comment]
@tirthbodawala This sounds really nice! I kinda need to deploy on firebase hosting, is there as way to handle it atm. with or without the plugin?

**Comment by yash-thakur** [comment]
@bytewiz https://github.com/firebase/reactfire/blob/master/docs/guide.md 
May be this can get you started.

**Comment by bytewiz** [comment]
@yash-thakur thanks, but I don't really need how firebase work, only how to deploy with firebase hosting with cloud functions, currently not possible from the `server.js` generated from the build

**Comment by dav-is** [comment]
@tirthbodawala What happened this weekend?

**Comment by dav-is** [comment]
I’m considering using https://aws.amazon.com/appsync/ instead of Firebase as it uses a universal standard (GraphQL) instead of an arbitrary one.

**Comment by tirthbodawala** [comment]
@bytewiz @dav-is getting pretty close with plugin and hooks. Updated the master branch to support paw_head & paw_footer hooks
Checkout `src/server.js`

**Comment by alsco77** [comment]
Hey guys, just wondering if anyone has got a solution for this? Or if it did get implemented in PawJS v2? Would like to host with firebase but pretty confused (++ this is my first PWA)

**Comment by satishblr** [comment]
Hi All, 

Can anyone tell me how to integrate Firebase into React-PWA? 

can this be done with current version?

Thanks a lot
Satish
