### ISSUE TITLE
add mobx example

### ISSUE THREAD

**Issue by goldylucks** [Atyantik/react-pwa#141]
I'm using this project and want to add mobx for state management.

I'm happy to PR documentation/example with some guidance!

Thoughts? @tirthbodawala

**Comment by goldylucks** [comment]
FYI: According to the [mobx docs](https://mobx.js.org/best/stateless-HMR.html#make-sure-your-top-level-component-is-a-stateful-observer), for hot reload to work we neet to make the root component a stateful observer.

**Comment by tirthbodawala** [comment]
@goldylucks I see MobX is very similar to Redux, is there any chance you can look at 
https://github.com/Atyantik/pawjs/tree/master/packages/pawjs-redux
and can integrate MobX?

**Comment by goldylucks** [comment]
@tirthbodawala I never done SSR on mobx, and haven't found a good tutorial or an updated repo with an example.

I got mobx + hot reload working on my SPA app without no SSR. I can make a PR/repo for that, and maybe someone in the future will pick up the gauntlet for mobx+SSR.
