### ISSUE TITLE
add HTTPS support for dev

### ISSUE THREAD

**Issue by goldylucks** [Atyantik/react-pwa#142]
I'm using features that require https. I've tried these combinations to start the dev server without success:

```bash
$ HTTPS=true npm start
$ npm start -- https
$ npm start -- --https
```

Also looked into `pawconfig.json` and there's no mention for `https`.

Webpack dev server has that option built in AFAIK. How can we implement this?

Happy to PR with some guidance :)

**Comment by gino8080** [comment]
up i need it also

**Comment by tirthbodawala** [comment]
@goldylucks @gino8080  we are adding a provision for the same, but till then I would recommend using nginx reverse proxy with SSL config in nginx.
