### ISSUE TITLE
ENV variables not working

### ISSUE THREAD

**Issue by goldylucks** [Atyantik/react-pwa#143]
I've tried in the 4 ways I've seen in the [docs] (https://www.reactpwa.com/docs/en/working-with-environment-variables.html), and every time `process.env` is an empty object.

Here's a minimal [repo](https://github.com/goldylucks/react-pwa), steps to reproduce:
```bash
$ https://github.com/goldylucks/react-pwa.git
$ npm run start-dot-env # or start-inline-env
```

I also tried the downloading latest pawjs with `$ npm i @pawjs/pawjs@latest` with same results.

@tirthbodawala am I missing something here?

**Comment by tirthbodawala** [comment]
Let me check this. I won't be able to get back to you till next 30 hours,
but I will try my best to look into all the issues.

**Comment by tirthbodawala** [comment]
@goldylucks I have corrected the code in branch `@pawjs/pawjs@ts` I will do a final release as well, but the branch is very stable. Please let me know if that works for you.

**Comment by goldylucks** [comment]
hey @tirthbodawala thanks for the update!

I switched to CRA2 so won't be needing this. Thanks a ton for all your time and help man!
