### ISSUE TITLE
set global varibal for internal API

### ISSUE THREAD

**Issue by lamvananh** [Atyantik/react-pwa#144]
Hi, How can i declare global variable in src/api/index.js ?
I has declare my variable as "var myItem = []" at the top of file. But every time a route triggerd, it's value always be reseted to initial ([] in this case)

**Comment by tirthbodawala** [comment]
@lamvananh you cannot do it like that. Please consider using Redux instead.

**Comment by lamvananh** [comment]
Hi, could you show me how to dispatch and consume a redux action in this project ?. I  don't find this in the document, it's talking about the config step only

**Comment by patelmayankce** [comment]
@lamvananh , you can checkout https://github.com/Atyantik/example-pawjs-redux
