### ISSUE TITLE
Change route outside a component

### ISSUE THREAD

**Issue by goldylucks** [Atyantik/react-pwa#145]
I'm in SPA & no SSR mode, and want to change the route outside a component. 
With react router 4, the way to do it is pass a history object to the browser, and then import it wherever you need it and call actions on it to change the route, as discussed [in their repo](https://github.com/ReactTraining/react-router/issues/5237#issuecomment-308245424)

In react-pwa the router config is abstracted away. How can we accomplish this?

would be happy to PR documentation with some guidance :)

**Comment by tirthbodawala** [comment]
@goldylucks with reactpwa you can access the history in use via `window.PAW_HISTORY` would that help?
Sorry for late reply.
