### ISSUE TITLE
dockerfile deployment

### ISSUE THREAD

**Issue by santalucial** [Atyantik/react-pwa#151]
i've seen you have worked with docker in the past, but i could not find a solution to the issue i'm experiencing, i'm using the following dockerfile to deploy the demo as is but i end up with a broken build and any page returns routing errors

> FROM node:8
> WORKDIR /app
> COPY . .
> RUN yarn
> RUN yarn build:demo
> VOLUME ["/app"]
> EXPOSE 3003
> CMD [ "nodejs", "dist/server.js" ] 

![image](https://user-images.githubusercontent.com/18719694/60008327-2d2ff080-9674-11e9-82af-a893f4f78652.png)

latest node images are unable to complete the build, v8 builds and i didn't notice any errors, but outputs a broken application, any idea as to why?

**Comment by itgelo** [comment]
remove `src` in .dockerignore file

**Comment by santalucial** [comment]
omg why, didn't even notice there was a dockerignore file as i added the dockerfile myself

**Comment by FibreFoX** [comment]
@santalucial is this issue fixed? If so, you might wanna close this issue 😃
