### ISSUE TITLE
Access to cookie object on server side

### ISSUE THREAD

**Issue by nodeEnthu** [Atyantik/react-pwa#157]
Hi,
Might be silly question

But how can I access the cookie object on server side

in the `pages/` dir I am logging the req object and it looks like this

```
{ updateSeo: [Function: updateSeo],
  route:
   { getRouteSeo: [Function: getRouteSeo],
     path: '/search/:cityName?',
     component:
      { [Function: C]
        displayName: 'withRouter(LoadableComponent)',
        WrappedComponent: [Function],
        propTypes: [Object],
        compiled: true },
     seo:
      { title: 'xxx' },
     exact: true,
     modules: [ './components/search' ] },
  match:
   { path: '/search/:cityName?',
     url: '/search/koala',
     isExact: true,
     params: { cityName: 'koala' } } }
```

**Comment by nodeEnthu** [comment]
bump!

**Comment by tirthbodawala** [comment]
@nodeEnthu You will probably need to implement universal cookies and their respective provider for client and server. We have already used it in one of our projects. Let me share it with you.

**Comment by nodeEnthu** [comment]
think you forgot to post the link .. never mind I got what you are saying
