### ISSUE TITLE
Warning in console: Upgrade Loadable

### ISSUE THREAD

**Issue by nodeEnthu** [Atyantik/react-pwa#158]
<img width="516" alt="Screen Shot 2019-10-01 at 11 43 11 PM" src="https://user-images.githubusercontent.com/9494357/66024402-a1b2d080-e4a8-11e9-9d21-2df94e37607f.png">

**Comment by tirthbodawala** [comment]
@nodeEnthu Thanks for raising the issue, we have solved this issue with latest implementation of @pawjs/pawjs. 
Please check the outdated packages via `npm outdated` and upgrade accordingly or you can simply upgrade to `npm i @pawjs/pawjs@next`
