### ISSUE TITLE
Run Build ReactPWA but only show like dir with item list folder

### ISSUE THREAD

**Issue by alhiro** [Atyantik/react-pwa#165]
Hello, i am interesting with this boilerplate.
But when i am trying to build for production only show like dir with list folder.

I am trying too with default create-react-app and running well.

I am use boilerplate in this git https://github.com/Atyantik/react-pwa and npm run build.
When trying to access it with server not display well like in development.
<img width="872" alt="Screen Shot 2019-12-11 at 15 37 42" src="https://user-images.githubusercontent.com/5734997/70605083-619c6680-1c2c-11ea-9386-4b5fa1960086.png">

Please help. Thank you

**Comment by tirthbodawala** [comment]
Hey @alhiro you need to run server.js via node, i.e.
```
cd <project-build>
node server.js
```

Once you run server.js, then the node server will start at the port specified.

**Comment by alhiro** [comment]
Awesome. It's working. Thank you so much!
