### ISSUE TITLE
async data

### ISSUE THREAD

**Issue by egaleme** [Atyantik/react-pwa#167]
Please what is the equivalent of getInitialProps in nextjs in ReactPwa

**Comment by tirthbodawala** [comment]
@egaleme check out the file: https://github.com/Atyantik/react-pwa/blob/master/src/pages/guest.js#L40 for details kindly check the section of routes for `skeleton-loading` now this loadData loads data from the server and pass it on to component `component: () => import('../components/skeleton-loading'),`

Please check out the file https://github.com/Atyantik/react-pwa/blob/master/src/components/skeleton-loading.js#L7 that utilizes the loadedData from 'loadData' as props and uses it to render in the component.

Hope that helps.

**Comment by egaleme** [comment]
Thanks it works. By the way why should anyone use ReactPwa against Nextjs. What are the advantages?

**Comment by tirthbodawala** [comment]
SEO friendly, multidomain support, image optimizations, any library extend-abilty, no dependency build, docker friendly etc.. I never got a chance to 100% check the difference, but I will conduct a benchmark for performance as well.

**Comment by egaleme** [comment]
Ok Cool. Looking forward to your benchmark.

**Comment by egaleme** [comment]
How do implement context api for ssr in ReactPwa
