### ISSUE TITLE
Progressive Image Loading Could be Refined

### ISSUE THREAD

**Issue by dav-is** [Atyantik/react-pwa#17]
The first image loaded that is small could be smaller. If you don't blur it you could probably get away with it being smaller, then blur it with CSS. That way you could also add a transition for a smooth unblur.

**Comment by tirthbodawala** [comment]
@dav-is thanks for opening the issue, we already have the provision for that. If we add '?placeholder to any image we import, it will present us with very small version of it. Let me add this to my todo of examples.

Thanks

**Comment by dav-is** [comment]
I’m worried you misunderstood. The placeholder images in your prior examples are blurred in the image, not CSS. And there is no Transition once the full image is loaded.

**Comment by tirthbodawala** [comment]
@dav-is ohh I see.. absolutely a transition would be good and yes I added the wrong example, if one uses 
‘’’
Import AbcImage from “./abc.png?sizes=100w+200w&lightweight”
‘’’

This will give you a really small version of image. So we will then implement a transition with css! That would be more UX friendly. 

Will definitely implement that.

**Comment by jhabdas** [comment]
Just gonna lob this in here as food for thought. https://images.guide/

**Comment by tirthbodawala** [comment]
Thanks @jhabdas that is very helpful. Thank you so much

**Comment by tirthbodawala** [comment]
@dav-is @jhabdas check this PR and https://react-pwa.now.sh/progressive-image-rendering
for implementation of progressive image with lightweight, I might not have got it 100% right, but you guys can share examples where I can make it even better. :)

**Comment by jhabdas** [comment]
Progress makes perfect! Thanks for all you do @tirthbodawala

**Comment by dav-is** [comment]
I did some testing and I don’t see any transition or blur.

**Comment by tirthbodawala** [comment]
@dav-is Right, I haven't added any transaction, I have just used lightweight with placeholder. Can you please share any example  where I can understand the functionality you are looking for ?

**Comment by dav-is** [comment]
```css
picture {
    filter: blur(25px);
    transition: blur .5s;
}
picture.is-loaded {
    filter: none;
}
```
When the full picture is loaded, add the `.is-loaded` class.
