### ISSUE TITLE
how to integrate REST api with PWA? any examples of doing this would be greatly appreciated

### ISSUE THREAD

**Issue by satishblr** [Atyantik/react-pwa#172]

**Comment by ericp96** [comment]
You could use the server.js file to add routes to express.

server.js
```js
const express = require('express');

class Server {
  constructor({ addMiddleware }) {
    const app = express();
    addMiddleware(app.get("/api/", (req, res) => res.send('OK')));
  }
}
```

**Comment by satishblr** [comment]
I added 
`POCKET_API_BASE=http://localhost:4000/api` this in my .env file 
created a HttpService helper like this
`const httpRequest = (url, options) => {
  console.log(`fetching data from :' ${url}`)
  return fetch(url, options);
};

export default httpRequest;
`

and using this as this

`import httpRequest from "../_shared/HttpService";

const requestOptions = {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password })
  };

  return httpRequest(`${process.env.POCKET_API_BASE}/users/register`, requestOptions)
    .then(handleResponse)
    .then(user => {
      // login successful if there's a user in the response
      return user;
    })
}
`

**Comment by ericp96** [comment]
Sorry - are you getting a 404?  What's your server.js file look like?

**Comment by satishblr** [comment]
this is my server.js file

`
import React from 'react';
import ReactPWAIcon from './resources/img/react-pwa.png';

export default class Server {
  // eslint-disable-next-line
  apply(serverHandler) {
    serverHandler.hooks.beforeHtmlRender.tapPromise('DSNPreCache', async (Application) => {
      const { htmlProps: { head } } = Application;
      head.push(<meta key="meta-theme-color" name="theme-color" content="#209cee" />);
      //
    });

    serverHandler.hooks.beforeHtmlRender.tapPromise('AddFavIcon', async (Application) => {
      const { htmlProps: { head } } = Application;
      head.push(<link key="favicon" rel="shortcut icon" type="image/png" href={ReactPWAIcon} />);
      return true;
    });

    serverHandler.hooks.beforeHtmlRender.tapPromise('AddGoogleTracking', async (Application) => {
      Application.htmlProps.footer.push(<script async key="googleanalyticslink" src="https://www.googletagmanager.com/gtag/js?id=UA-" />);
      Application.htmlProps.footer.push(<script
        key="googleanalyticsscript"
        // eslint-disable-next-line
        dangerouslySetInnerHTML={{
          __html: `window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'UA-');`,
        }}
      />);
    });
  }
}

`

**Comment by ericp96** [comment]
You need to add an api by hooking into the express middleware:
```js
export default class Server {
  constructor({ addMiddleware }) {
    const app = express();
    addMiddleware(app.get("/api/", (req, res) => res.send('OK')));
  }
}
```

**Comment by satishblr** [comment]
But what if I have a separate express REST API project and want to make calls from PWA app? is there a  best practice? I am new to this PWA and using react-pwa boiler plate.

**Comment by ericp96** [comment]
You should be able to call it the same as you would any other PWA.  

There is one caveat to this that I'm aware of and that's if you are using the server side rendering option where the target destination changes between the server and the client.  An example of this would be in a containerized environment (e.g. Docker) where localhost means something very different when done in a docker container vs in a browser.
