### ISSUE TITLE
Firebase integration

### ISSUE THREAD

**Issue by satishblr** [Atyantik/react-pwa#175]
Hi 

I am trying to use Firebase in react PWA app. I am not able to install 
```nodejs
npm install --save firebase
```

I get this error

npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.24.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I would like to use google authentication using the below documentation
`https://firebase.google.com/docs/auth/web/google-signin`

any help is greatly appreciated 

Thanks

**Comment by tirthbodawala** [comment]
@satishblr  can you please check the issue at node-pre-gyp?
https://github.com/mapbox/node-pre-gyp/issues/381

**Comment by satishblr** [comment]
Thanks for the link. I was behind a proxy I was able to install firebase but how do I add firebase plugin into ReactPwa? any example code on how to do it?

Thanks

**Comment by matextrem** [comment]
@satishblr Did you find any workaround for this?

**Comment by tirthbodawala** [comment]
@matextrem @satishblr If firebase acts similar at frontend and backend, It should work perfectly fine.
What and how are you expecting from firebase data?
Also, if you want me to write down a tutorial for the same, I can do that. Please let me know what you need in the tutorial to solve your issues?

**Comment by matextrem** [comment]
I would like to have an approach about how to integrate firebase (auth and database) using this boilerplate.

Thanks!

**Comment by satishblr** [comment]
> @satishblr Did you find any workaround for this?

not yet

**Comment by satishblr** [comment]
> @matextrem @satishblr If firebase acts similar at frontend and backend, It should work perfectly fine.
> What and how are you expecting from firebase data?
> Also, if you want me to write down a tutorial for the same, I can do that. Please let me know what you need in the tutorial to solve your issues?

Thanks for the reply. sorry I was out. I am trying to integrate basic user authentication and integration within my app. so I don't have to write everything from scratch.

Any tutorial is greatly appreciated

Thanks
