### ISSUE TITLE
lodash.js warning

### ISSUE THREAD

**Issue by rei-gun** [Atyantik/react-pwa#179]
This warnign occurs "npm start" and building

`[BABEL] Note: The code generator has deoptimised the styling of C:\repo\node_modules\lodash\lodash.js as it exceeds the max of 500KB.`

Is there any way to fix it?

**Comment by tirthbodawala** [comment]
@rei-gun it is ok to ignore the warning. We are using lodash es6 modules in ReactPWA so the warning only goes for development mode.
