### ISSUE TITLE
Stuck at Applying patches...

### ISSUE THREAD

**Issue by faizannu** [Atyantik/react-pwa#183]
while running npm install it stuck at Applying patches... 
same happen on running with sudo too

**Comment by faizannu** [comment]
![Screenshot from 2020-05-03 08-37-12](https://user-images.githubusercontent.com/38948883/80897727-9911c980-8d19-11ea-92d0-1e6e9490aec9.png)

**Comment by sreeharicubet** [comment]
I too have the same issue....Is there any solution to rectify this? 
Thank you!

**Comment by pmbuban** [comment]
Having this issue as well

**Comment by tirthbodawala** [comment]
@faizannu @sreeharicubet @pmbuban apologies for late reply, it was stuck due to synk patches. Have revemod it for for now. Please try with master code base.
