### ISSUE TITLE
Upgrade guide required

### ISSUE THREAD

**Issue by bcalik** [Atyantik/react-pwa#184]
Description of this repo says "An upgradable boilerplate ...", but there isn't any upgrade guide available.

**Comment by tirthbodawala** [comment]
Apologies for the same, I am working on Docs. But by upgradable, we mean,
you can upgrade from any version of PawJS (core library) to new version,
without breaking the application.

**Comment by bcalik** [comment]
Sorry I may still not be able to understand what actually "upgradable" refer to, thats sounds a little weird to me. For example package.json doesn't contain react library itself and pawjs core actually require react, and react itself may get a breaking change. So pawjs would bump the version to 4 from 3, and that is not upgradable.

**Comment by tirthbodawala** [comment]
I undesratand, and that is a very good point actually, I am now planning to
move react as Peer Dependency, thus handled by user himself. Thank you for
pointing that out

**Comment by bcalik** [comment]
That was an example, I'm not really sure if you should move react as peer dependency or not. But thank you for your reply and interest.

**Comment by tirthbodawala** [comment]
No, Thank you. I will see what term I should use as description so it
represents what it exactly does. It has been a valuable conversation
