### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by desaikalpesh34** [Atyantik/react-pwa#187]
npm start not working
check screenshot i have  attached.
i am using node 6.9.0
![Screenshot_2](https://user-images.githubusercontent.com/10667017/86090393-a0f6ab80-bac7-11ea-9df4-d1712e985f5b.png)

**Comment by michalko** [comment]
same

**Comment by vassilux** [comment]
same for me, any idea ?

**Comment by tirthbodawala** [comment]
@desaikalpesh34 @vassilux  @michalko, I know this is late by 1 year, my hearty apologies, with upgrades of packages we have solve this issue, Please use latest code to reflect the changes.
