### ISSUE TITLE
npm start fails on Windows.

### ISSUE THREAD

**Issue by Sbrunelli433** [Atyantik/react-pwa#189]
I believe this is a known bug, I see there are other open issues that have little to no feedback on this.. Opening a new issue to push the envelope. 

Currently using node 12.14.0 64-bit executable. 

![terminal](https://user-images.githubusercontent.com/49485252/87809108-6d828380-c820-11ea-964d-4f02b76f5d84.JPG)
![log](https://user-images.githubusercontent.com/49485252/87809110-6e1b1a00-c820-11ea-9fd4-856cf0a4abc1.JPG)

**Comment by tirthbodawala** [comment]
Hi @Sbrunelli433,
thank you for pointing this out. Apologies, the last 2 weeks have been really busy. I will check this and get back to you at the soonest.

**Comment by vassilux** [comment]
I got same and use node v10.15.3 in Windows 10 
Any idea ?

**Comment by tirthbodawala** [comment]
@vassilux  Apologies this is issue faced due to Chokidar dependency in windows. We are working on it
