### ISSUE TITLE
deployment guide on heroku 

### ISSUE THREAD

**Issue by vijaykarani333** [Atyantik/react-pwa#192]
Following this [guide](https://www.reactpwa.com/docs/en/deploying-to-heroku.html) trying to deploy the it on heroku since when I run it locally it, it didn't prompt me to "install" it  nor provide the install option like the live demo. 
Any hit for the error. Thank you. 

Build Seem Successful:
`

-----> Node.js app detected

       

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NODE_ENV=production

       NODE_MODULES_CACHE=true

       NODE_VERBOSE=false

       

-----> Installing binaries

       engines.node (package.json):  unspecified

       engines.npm (package.json):   unspecified (use default)

       

       Resolving node version 12.x...

       Downloading and installing node 12.18.3

       Using default npm version: 6.14.6

       

-----> Installing dependencies

       Installing node modules

       

       > ejs@2.7.4 postinstall /tmp/build_e9796f73/node_modules/ejs

       > node ./postinstall.js

       

       

       > sharp@0.23.4 install /tmp/build_e9796f73/node_modules/sharp

       > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

       

       info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz

       

       > cwebp-bin@5.1.0 postinstall /tmp/build_e9796f73/node_modules/cwebp-bin

       > node lib/install.js

       

         ⚠ Command failed: /tmp/build_e9796f73/node_modules/cwebp-bin/vendor/cwebp -version

       /tmp/build_e9796f73/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

       

       

         ⚠ cwebp pre-build test failed

         ℹ compiling from source

         ✔ cwebp built successfully

       

       > node-sass@4.14.1 install /tmp/build_e9796f73/node_modules/node-sass

       > node scripts/install.js

       

       Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-72_binding.node

       Download complete

       Binary saved to /tmp/build_e9796f73/node_modules/node-sass/vendor/linux-x64-72/binding.node

       Caching binary to /tmp/npmcache.8cQSW/_cacache/node-sass/4.14.1/linux-x64-72_binding.node

       

       > node-sass@4.14.1 postinstall /tmp/build_e9796f73/node_modules/node-sass

       > node scripts/build.js

       

       Binary found at /tmp/build_e9796f73/node_modules/node-sass/vendor/linux-x64-72/binding.node

       Testing binary

       Binary is fine

       

       > fsevents@1.2.13 install /tmp/build_e9796f73/node_modules/fsevents

       > node install.js

       

       

       Skipping 'fsevents' build as platform linux is not supported

       

       > core-js@2.6.11 postinstall /tmp/build_e9796f73/node_modules/core-js

       > node -e "try{require('./postinstall')}catch(e){}"

       

       

       > universal-url-lite@2.0.0 install /tmp/build_e9796f73/node_modules/universal-url-lite

       > node scripts/build-lite.js

       

       

       > core-js@3.6.5 postinstall /tmp/build_e9796f73/node_modules/@snyk/cocoapods-lockfile-parser/node_modules/core-js

       > node -e "try{require('./postinstall')}catch(e){}"

       

       

       > core-js-pure@3.6.5 postinstall /tmp/build_e9796f73/node_modules/core-js-pure

       > node -e "try{require('./postinstall')}catch(e){}"

       

       

       > gifsicle@4.0.1 postinstall /tmp/build_e9796f73/node_modules/gifsicle

       > node lib/install.js

       

         ✔ gifsicle pre-build test passed successfully

       

       > pngquant-bin@5.0.2 postinstall /tmp/build_e9796f73/node_modules/pngquant-bin

       > node lib/install.js

       

         ✔ pngquant pre-build test passed successfully

       

       > optipng-bin@6.0.0 postinstall /tmp/build_e9796f73/node_modules/optipng-bin

       > node lib/install.js

       

         ✔ optipng pre-build test passed successfully

       

       > mozjpeg@6.0.1 postinstall /tmp/build_e9796f73/node_modules/mozjpeg

       > node lib/install.js

       

         ✔ mozjpeg pre-build test passed successfully

       added 2261 packages in 85.175s

       

-----> Build

       Running build

       

       > react-pwa@2.2.10 build /tmp/build_e9796f73

       > pawjs --no-cache --env-config-path=./.prod.env --env=production build

       

       

       ===================================================

         Building application...

         This may take time depending on the application size.

         Thank you for your patience.

       ===================================================

       

       Hash: d40009b1a1b20e4d8908

       Child web:

           Hash: d40009b1a1b20e4d8908

           Time: 45422ms

           Built at: 08/12/2020 11:46:52 PM

           PublicPath: /

                                                                    Asset       Size  Chunks                                Chunk Names

                                             css/9cbbdeda6099140a4014.css   53 bytes       3  [emitted] [immutable]         

                                             css/d40009b1a1b20e4d8908.css   2.42 KiB       0  [emitted] [immutable]         client

                                             css/f1b34b4afe83c31a8975.css    190 KiB       1  [emitted] [immutable]         vendors~client

             images/27b33a98f515e1be9911cd7535e33f0a-css-global-local.png   20.5 KiB          [emitted]                     

                      images/3cbcdad7e33b78665bb0aeda852549c4-dog-cat.jpg   17.4 KiB          [emitted]                     

             images/42e3d7b4f847d7343ef2409e8a466dac-pwa-icon-192x192.png   4.37 KiB          [emitted]                     

                     images/5229ff33f8d216ed9b83ade02136d274-dog-cat.webp   14.3 KiB          [emitted]                     

                      images/53d63b4687fc818c0604ef1ce3e65d0a-dog-cat.jpg    114 KiB          [emitted]                     

                        images/58fa70f46b9b972807db9b0e44256d13-login.png   7.49 KiB          [emitted]                     

           images/5fe5cd5d6ef18025e5c9001c899dc92a-home-splash-screen.png   4.15 KiB          [emitted]                     

                      images/630e27a408ae4e27929dd477a112420a-dog-cat.jpg    9.4 KiB          [emitted]                     

                     images/7395b692556e01f2cae4ead5a90ac25c-dog-cat.webp   30.2 KiB          [emitted]                     

                     images/7f10134c6ec1d625c82841be0667ab89-dog-cat.webp   39.7 KiB          [emitted]                     

                     images/94902d6c58cbb2196044f7b7e07c9fed-dog-cat.webp     21 KiB          [emitted]                     

                     images/95d550f67a5263c8302575c4b2b496f3-dog-cat.webp   7.49 KiB          [emitted]                     

             images/b715dfcda781921e7a49e90e223f3513-pwa-icon-512x512.png   10.7 KiB          [emitted]                     

                     images/c0612d88d0644b805a9669c95b1b6e1d-features.png   42.6 KiB          [emitted]                     

             images/d428b9529980b59b461bff8501f16d3a-skeleton-loading.png   6.37 KiB          [emitted]                     

                      images/e489e2fe71a125185596f3e20c03e79c-dog-cat.jpg   38.6 KiB          [emitted]                     

                      images/eb9283a72019f2cd75ef49b1f786ffcb-dog-cat.jpg   51.8 KiB          [emitted]                     

           images/f1120f5c82a108da2cb9645202fdb6dc-image-optimization.png    895 KiB          [emitted]              [big]  

                      images/f7b8964944bfb18b923d7ab9d4b5c17c-dog-cat.jpg   26.9 KiB          [emitted]                     

                                               js/2847dd535ccccb1f0a72.js   3.57 KiB       5  [emitted] [immutable]         

                                               js/28e270fa0079137e53ca.js    8.1 KiB       9  [emitted] [immutable]         

                                               js/43cd6aff54473ea830d5.js   8.31 KiB       8  [emitted] [immutable]         

                                               js/6781fbebf95e094b230e.js   9.85 KiB       7  [emitted] [immutable]         

                                               js/90987407d9f0bfb24816.js   10.2 KiB       2  [emitted] [immutable]         

                                               js/9cbbdeda6099140a4014.js    6.3 KiB       3  [emitted] [immutable]         

                                               js/9e994dcd8c8a41ded70f.js  587 bytes      12  [emitted] [immutable]         

                                               js/ab9767824f5d0c3a4d33.js   7.07 KiB       6  [emitted] [immutable]         

                                               js/c55d739d2fb07877d5af.js   14.2 KiB       4  [emitted] [immutable]         

                                               js/d1fb1aa33e70ecbe7e53.js    6.4 KiB      10  [emitted] [immutable]         

                                               js/d40009b1a1b20e4d8908.js   15.9 KiB       0  [emitted] [immutable]         client

                                               js/de185e1b9b27a9a37c8b.js   75.9 KiB      11  [emitted] [immutable]         

                                               js/f1b34b4afe83c31a8975.js    423 KiB       1  [emitted] [immutable]  [big]  vendors~client

                                                                    sw.js    140 KiB          [emitted]                     

           

           WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).

           This can impact web performance.

           Assets: 

             images/f1120f5c82a108da2cb9645202fdb6dc-image-optimization.png (895 KiB)

             js/f1b34b4afe83c31a8975.js (423 KiB)

           

           WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.

           Entrypoints:

             client (632 KiB)

                 css/f1b34b4afe83c31a8975.css

                 js/f1b34b4afe83c31a8975.js

                 css/d40009b1a1b20e4d8908.css

                 js/d40009b1a1b20e4d8908.js

           

           Child InjectManifest:

               PublicPath: /

                1 asset

           Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js??ref--10-1!../node_modules/sass-loader/dist/cjs.js??ref--10-2!resources/css/util.scss:

               PublicPath: /

           Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js??ref--5-1!components/local-styles.css:

               PublicPath: /

           Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/bulma/css/bulma.min.css:

               PublicPath: /

           Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js??ref--6-1!resources/css/global.css:

               PublicPath: /

       Hash: 1e91fce0f2f745d2c7ba

       Child server:

           Hash: 1e91fce0f2f745d2c7ba

           Time: 14507ms

           Built at: 08/12/2020 11:47:07 PM

           PublicPath: /

                                                                 Asset      Size  Chunks             Chunk Names

           build/images/b715dfcda781921e7a49e90e223f3513-react-pwa.png  10.7 KiB          [emitted]  

                                                            server.css  53 bytes       0  [emitted]  main

                                                             server.js   1.1 MiB       0  [emitted]  main

           Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js??ref--5-1!components/local-styles.css:

               PublicPath: /

       

-----> Caching build

       - node_modules

       

-----> Pruning devDependencies

       audited 2699 packages in 18.245s

       

       75 packages are looking for funding

         run `npm fund` for details

       

       found 5243 vulnerabilities (5238 low, 5 high)

         run `npm audit fix` to fix them, or `npm audit` for details

       

-----> Build succeeded!

-----> Discovering process types

       Procfile declares types -> web

-----> Compressing...

       Done: 114M

-----> Launching...

       Released v3

       https://salty-beyond-50241.herokuapp.com/ deployed to Heroku`

The error:
2020-08-12T23:48:09.600340+00:00 app[web.1]: Listening to http://0.0.0.0:3003
2020-08-12T23:49:07.932312+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-08-12T23:49:07.958422+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-08-12T23:49:08.047250+00:00 heroku[web.1]: Process exited with status 137
2020-08-12T23:49:08.097597+00:00 heroku[web.1]: State changed from starting to crashed
2020-08-12T23:49:08.099376+00:00 heroku[web.1]: State changed from crashed to starting
2020-08-12T23:49:23.993561+00:00 heroku[web.1]: Starting process with command `node dist/server.js`
2020-08-12T23:49:26.888909+00:00 app[web.1]: Listening to http://0.0.0.0:3003
2020-08-12T23:50:24.046095+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-08-12T23:50:24.072486+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-08-12T23:50:24.166158+00:00 heroku[web.1]: Process exited with status 137
2020-08-12T23:50:24.222050+00:00 heroku[web.1]: State changed from starting to crashed
2020-08-12T23:51:35.482163+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=salty-beyond-50241.herokuapp.com request_id=33997c2c-1178-451f-bff5-51c30701452a fwd="99.203.43.205" dyno= connect= service= status=503 bytes= protocol=https
2020-08-12T23:51:37.287714+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=salty-beyond-50241.herokuapp.com request_id=4bc1cd6e-508f-4da1-8c85-e0d563c78d80 fwd="99.203.43.205" dyno= connect= service= status=503 bytes= protocol=https
2020-08-13T00:11:14.873222+00:00 heroku[web.1]: State changed from crashed to starting
2020-08-13T00:11:30.259571+00:00 heroku[web.1]: Starting process with command `node dist/server.js`
2020-08-13T00:11:32.305239+00:00 app[web.1]: Listening to http://0.0.0.0:3003
2020-08-13T00:12:30.622751+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-08-13T00:12:30.645174+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-08-13T00:12:30.737703+00:00 heroku[web.1]: Process exited with status 137
2020-08-13T00:12:30.791676+00:00 heroku[web.1]: State changed from starting to crashed
2020-08-13T00:55:30.399634+00:00 heroku[web.1]: State changed from crashed to starting
2020-08-13T00:55:47.047466+00:00 heroku[web.1]: Starting process with command `node dist/server.js`
2020-08-13T00:55:49.304207+00:00 app[web.1]: Listening to http://0.0.0.0:3003
2020-08-13T00:56:47.499520+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-08-13T00:56:47.519728+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-08-13T00:56:47.580437+00:00 heroku[web.1]: Process exited with status 137
2020-08-13T00:56:48.615522+00:00 heroku[web.1]: State changed from starting to crashed
2020-08-13T00:56:50.042107+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=salty-beyond-50241.herokuapp.com request_id=2d749a7e-2909-4eb0-b963-b6b36792249b fwd="99.203.43.205" dyno= connect= service= status=503 bytes= protocol=https
2020-08-13T00:56:50.298533+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=salty-beyond-50241.herokuapp.com request_id=e7ceb61a-fb30-4a5e-9dd5-9c2b48d023bd fwd="99.203.43.205" dyno= connect= service= status=503 bytes= protocol=https
2020-08-13T00:56:50.492548+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=salty-beyond-50241.herokuapp.com request_id=73cdb3ac-b425-4db2-9711-d56a33ee5128 fwd="99.203.43.205" dyno= connect= service= status=503 bytes= protocol=https

**Comment by shubham49** [comment]
Heroku assigns PORT to node automatically so we don't need to specify PORT.
comment out the port from .prod.env
#PORT=3003
