### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by 4LostGreyWolf** [Atyantik/react-pwa#193]
![FD2BE37E-782D-4dcd-86A4-37A514F48964](https://user-images.githubusercontent.com/20333205/91398798-5f883f80-e86f-11ea-8a65-e3d0d94d8c33.png)

 
 npm run start的时候报错

**Comment by tirthbodawala** [comment]
@4LostGreyWolf  It is an error we are aware of and are working on it. It is due to duplicator issue.

**Comment by tirthbodawala** [comment]
@4LostGreyWolf please use the latest code base to fix the issue.
