### ISSUE TITLE
Redux Offline instead of API caching

### ISSUE THREAD

**Issue by dav-is** [Atyantik/react-pwa#20]
Here’s an interesting article on this: https://hackernoon.com/introducing-redux-offline-offline-first-architecture-for-progressive-web-applications-and-react-68c5167ecfe0

Note: the repo for react offline is going through ownership changes currently

**Comment by jhabdas** [comment]
Jani is a smart guy and has a good pulse on RN. There are [some discussion](https://github.com/callemall/material-ui/issues/593) regarding the confluence of native vs. Web which calls to mind the app vs. web debates we had years ago starting to form in the community it seems—as we can see with [this discussion](https://github.com/callemall/material-ui/issues/593) on `material-ui` where @necolas, a former designer at Twitter and creator of SuitCSS, discuss adding [`react-native-web`](https://github.com/necolas/react-native-web). Just another lob.

**Comment by dav-is** [comment]
I’m curious to what you think.

**Comment by tirthbodawala** [comment]
We have removed API caching and would allow the user to configure service worker to handle API caching manually. Thus closing the discussion.
