### ISSUE TITLE
Issue while npm start

### ISSUE THREAD

**Issue by zeeking786** [Atyantik/react-pwa#203]
I am getting ``` UnhandledPromiseRejectionWarning``` -
![Screenshot (13)](https://user-images.githubusercontent.com/61353037/126890305-d742fdbe-a314-481a-a852-78b42f808029.png)

I need solution for this in windows , so please help me !!!

Node version - v14.17.3
Npm version - 6.14.13
Advance thanks👍

**Comment by tirthbodawala** [comment]
@zeeking786 We have solved the issue, can you please try with latest code base?
