### ISSUE TITLE
How To Build APK File For Android & IOS ?

### ISSUE THREAD

**Issue by VijiHithub** [Atyantik/react-pwa#208]
Hi Team , 

I Have Clone This Code and Run Successfully. 

But I don't know how to build APK Files. 

Kindly share the process ASAP. 

Thanks in Advance !!!

**Comment by mnakka9** [comment]
https://www.pwabuilder.com/

https://amlanscloud.com/reactnativepwa/ --- instructions are here, search for Test for PWA and you will find info on how to get APK and submit it to play store
