### ISSUE TITLE
sitemap.xml and robot

### ISSUE THREAD

**Issue by gmchaturvedi1** [Atyantik/react-pwa#21]
hi,
i am new  to this where we can ut sitemap.xml and robot files .

regrds
gmchaturvedi

**Comment by tirthbodawala** [comment]
That is a very good question, How did I missed it.. :D 
Well anything in src/public/ folder is available via <url>/public/ But I know its not appropriate to add robots.txt & sitemap.xml with prefix like <url>/public/robot.txt or <url>/public/sitemap.xml

Its a bug and would be solved. 

@gmchaturvedi1 Are there any other files that needs to be directly accessible via root of url? 
i.e. <url>/robot.txt  or <url>/abc.xyz ?

**Comment by dav-is** [comment]
> Are there any other files that needs to be directly accessible via root of url?

favicon.ico, the sw.js if you don’t already have those in mind

**Comment by tirthbodawala** [comment]
@dav-is favicon is already handled

**Comment by tirthbodawala** [comment]
@gmchaturvedi1 With latest push on master branch if you add sitemap.xml/robot.txt to src/public folder it should be accessible via <url>/robot.txt or <url>/sitemap.xml.
