### ISSUE TITLE
Dockerizing the application

### ISSUE THREAD

**Issue by mrtysn** [Atyantik/react-pwa#24]
Using docker in order to deploy and easily scale the application is a necessary milestone. I believe you guys already have this as a WIP and if you were to share the progress, more people would be able to contribute.

**Comment by jhabdas** [comment]
Here's a recent example of adding Docker to a Webpack boilerplate from @eyedol, in case it proves useful: https://github.com/netlify/victor-hugo/pull/25. The team at Netlify opted against adding Docker but I strongly encourage it.

Here are some other Docker resources:
- https://habd.as/swarm-clusters-digital-ocean/ — how to swarm (scale horizontally) on a VPS
- https://habd.as/simple-websites-jekyll-docker/ — packaging a static website with Docker
- https://github.com/jhabdas/react-native-webpack-starter-kit — Webpack + Docker

**Comment by dav-is** [comment]
Where are we stuck on docker implementation? It should be relatively simple.

**Comment by tirthbodawala** [comment]
@dav-is and @jhabdas we are almoat there, it was Diwali vacation in India, which ended today, thus can focus on docker now. I think, it shouldn’t take more than 2 days to complete it. i.e. by tomorrow..

**Comment by tirthbodawala** [comment]
One can now easily manage docker-build with this enhancement given Docker is properly configured and the terminal that is running the nodejs has access to docker command.

Steps to works with docker

`yarn docker:dev:image` 
Will create a development image named "react-pwa" which will be used during application development and running.
If anything new is added to package.json `yarn docker:dev:image` must be rebuild to get the latest nodejs packages

`yarn docker:dev:start`  will start the application in docker mode. 
`yarn docker:prod:build`  will start the build the application for production 
`yarn docker:prod:image`  will create a docker image that can be deployed easily to any docker-hub and can create production containers
`yarn docker:prod:start` will start the application in production mode, its necessary to create docker:prod:image prior to docker:prod:start

**Comment by jhabdas** [comment]
nice cli! hope you had a great Diwali!!!

**Comment by tirthbodawala** [comment]
Thanks @jhabdas Yaah, it was great. I got to code a lot along with spending time with family and having beer at night, most heavenly experience :)
