### ISSUE TITLE
Fresh install bug

### ISSUE THREAD

**Issue by lukaszzdanikowski** [Atyantik/react-pwa#25]
yarn run v1.2.1
node v8.7.0
After repository clone and yarn install && yarn start i get:
ERROR in ./src/resources/images/mario-large.png?sizes=100w+200w+400w+800w&placeholder&lightweight
esourcesimagesmario-large.png' in 'C:\sandbox\workspace\react-pwa\src\resources\images'
 @ ./src/resources/images/mario-large.png?sizes=100w+200w+400w+800w&placeholder&lightweight 12:17-199 24:17-199
 @ ./src/app/components/progressive-image/progressive-image.js
 @ ./src/pages/progressive-image-rendering.js
 @ ./src/routes.js
 @ ./src/core/client/dev.client.js
 @ multi babel-polyfill react-hot-loader/patch ./src/core/client/dev.client.js webpack-hot-middleware/client?name=common-client&path=/__hmr_update&timeout=2000&overlay=true

ERROR in ./src/resources/images/mario-large.png?sizes=100w+200w+400w+800w&placeholder
esourcesimagesmario-large.png' in 'C:\sandbox\workspace\react-pwa\src\resources\images'
 @ ./src/resources/images/mario-large.png?sizes=100w+200w+400w+800w&placeholder 12:17-200 24:17-200
 @ ./src/app/components/home/home.js
 @ ./src/pages/home.js
 @ ./src/routes.js
 @ ./src/core/client/dev.client.js
 @ multi babel-polyfill react-hot-loader/patch ./src/core/client/dev.client.js webpack-hot-middleware/client?name=common-client&path=/__hmr_update&timeout=2000&overlay=true

**Comment by tirthbodawala** [comment]
@lukaszzdanikowski can you please provide OS details?

**Comment by tirthbodawala** [comment]
@lukaszzdanikowski well it worked for me in Ubuntu, not sure why is it giving an error in Windows. Can you please share OS details as well?

**Comment by lukaszzdanikowski** [comment]
@tirthbodawala Win10 Pro x64  v1703

**Comment by tirthbodawala** [comment]
Thanks @lukaszzdanikowski I have mac and Ubuntu. will get access to Windows tomorrow morning IST. i.e. approx 16 hours from now. I will look into it asap. Thanks for reporting.

**Comment by lukaszzdanikowski** [comment]
@tirthbodawala thanks, it looks like slashes in on of the plugins get interpreted, that is why the file urls is changed to: esourcesimagesmario-large.png

**Comment by tirthbodawala** [comment]
Right. I am sure its something related to windows path problem. Getting a VM to solve the issue asap. If you find the bug please share the PR. 
Thanks

**Comment by lukaszzdanikowski** [comment]
I think that the issue is with pwa-srcset-loader. The npm version is not aligned with github repository (could you add version tags?). In the version that is published through npm the createPlaceholderRequest generates unescaped require if you add JSON.stringify there it should be ok. @tirthbodawala

**Comment by tirthbodawala** [comment]
@lukaszzdanikowski Thank you so much for the wonderful PR in pwa-srcset-loader. I have merged it and upgraded the repo to use latest pwa-srcset-loader. Please let me know if you are still facing the issue. 

Also I have added Docker support thus making it workable everywhere. 
Thanks for your contribution.
