### ISSUE TITLE
routes-loader doesn't run on Windows

### ISSUE THREAD

**Issue by lukaszzdanikowski** [Atyantik/react-pwa#26]
On Windows development env the webpack route-loader is not run, thus bundleKey is not added to page's js files and the 404 info is displayed all the time

**Comment by tirthbodawala** [comment]
Thanks for reporting the bug @lukaszzdanikowski Have you tried dockerizing the application ? 
I will test this in windows right away though.

**Comment by tirthbodawala** [comment]
@lukaszzdanikowski The problem was not with routes loader but with regex of the pages, that we use loader for thus changed the regex to support both "\" & "/" I tested it on windows 10 Pro and is working just fine now. Please let me know if you still face any issue.
