### ISSUE TITLE
doesn't have pwa on subroutes

### ISSUE THREAD

**Issue by AgentChris** [Atyantik/react-pwa#31]
when i hit the refresh button the app brokes

**Comment by tirthbodawala** [comment]
@AgentChris. The react-pwa.now.sh was not updated properly. We have shifted the demo app to 
https://demo.reactpwa.com, it should work now. Also regarding "Doesn't refresh on pwa subroutes." works on Linux, Windows, Mac.

If you are still facing the issue. please re-open the issue.
