### ISSUE TITLE
Strange behavior in prod and dev env (duplicate head)

### ISSUE THREAD

**Issue by miladb** [Atyantik/react-pwa#34]
Thank you for this awesome boilerplate.

I have a strange behavior with css.

In dev mode, all css are loaded.
In production, the head (metas + css) document of page is duplicated.
You can see an example in the attachement file (duplication of metas) : 

![react-pwa](https://user-images.githubusercontent.com/1544276/32377241-468785a6-c0a7-11e7-95b3-be471de575cb.png)

Thank you

**Comment by tirthbodawala** [comment]
@miladb, I see it is definitely a bug, need to remove the duplicate from prod mode. thanks for noticing

**Comment by jhabdas** [comment]
There’s gotta be a joke in here somewhere about giving too much head...
