### ISSUE TITLE
Doesn't seems to work as PWA on iPhone

### ISSUE THREAD

**Issue by mohammedzamakhan** [Atyantik/react-pwa#35]
I tried the website on my iPhone, didn't get the notification to add on home screen, and also if I save it on my home screen manually, and open it, it opens as a website, on safari, not full screen or any thing pwa :/

**Comment by tirthbodawala** [comment]
PWA is limited to some browsers, right now supported on android phones. Safari is not yet supported.

**Comment by mohammedzamakhan** [comment]
I know of other PWA's that work on my iPhone?!!! Like not all the features, but at least full screen and stuff

**Comment by dav-is** [comment]
I believe there’s some special meta tags for fullscreen support but that’s it. Are those tags missing?

**Comment by jhabdas** [comment]
Safari Mobile got fetch in iOS 10.1. If Cache API thingie for PWAs still isn’t supported for offline support I imagine it’s coming. What if a user is using Chrome on iOS? TBH it’s kind of hard to ignore 50% of the smartphone market.

Sent from Safari Mobile on my iPhone.

**Comment by tirthbodawala** [comment]
@jhabdas There are rumors regarding IOS implementation of PWA. But one thing is for sure, even if it's not PWA the boilerplate will function fast with code splitting and SSR! 
@dav-is @mohammedzamakhan I will add the apple full screen meta and Icons, it is in the todo-list :)

**Comment by dav-is** [comment]
Chrome on iOS still uses WebKit. Apple has been holding back development of chrome features like the payment API, PWAs, web notifications, etc. it’s really one of my only disappointments with Apple right now.

Although, I’m a bit worried there’s a conflict of interest when it comes to implementing PWAs in iOS as Apple makes quite a bit of money from the AppStore. Imagine if everyone started using pwas exclusively (which I think could be the future). Apple wouldn’t be able to make money from paid apps anymore. I bet they initially hoped PWAs would die out like a lot of web standards, this is why  they don’t have a proper implementation.

**Comment by tirthbodawala** [comment]
@dav-is @jhabdas @mohammedzamakhan I have added appropriate meta tags thus supporting the fullscreen view in IOS as well.  Making more changes for apple app icon and shall update master accordingly.
