### ISSUE TITLE
Error 500 before loading home page

### ISSUE THREAD

**Issue by jaysondaquer** [Atyantik/react-pwa#39]
Hi, we're trying to test this out on our server and we're able to deploy and run it properly. The only issue we have now is it always shows the Error 500 page before loading the actual landing page. https://react-pwa-dev.istackmanila.com/about

**Comment by tirthbodawala** [comment]
@jaysondaquer did you installed any library after setup? If you used a library that uses window or document to function and the library is called in any child imports of server then we usually see a 500 server error. 
Can you please share more details?

**Comment by jaysondaquer** [comment]
![image](https://user-images.githubusercontent.com/7529733/32492700-2fae9502-c3f6-11e7-8c77-73ab515b93cb.png)
Hi @tirthbodawala  not sure if this cause the issue. I think the generation of the manifest.json throws an error because it cannot find the expected icon's naming conventions.

**Comment by jaysondaquer** [comment]
![image](https://user-images.githubusercontent.com/7529733/32492787-7354571a-c3f6-11e7-8e10-2976fc4567c8.png)
it only shows the error 500 then skips and loads the actual home page. this cause an issue when being scraped by facebook as they initially scraped the errorPage

![image](https://user-images.githubusercontent.com/7529733/32492849-a100c9dc-c3f6-11e7-91a8-4240edf63e11.png)

**Comment by jaysondaquer** [comment]
![image](https://user-images.githubusercontent.com/7529733/32492927-f38c9c30-c3f6-11e7-85d8-9e17348361d9.png)
not sure how are you able to generate this manifest.json on your demo site given this pattern 

>  "src": require(`../../resources/images/pwa/icon-${size}x${size}.png`),

**Comment by jaysondaquer** [comment]
just an update, we've already updated our build scripts and now able to load the manifest file. though we still see the Error 500 issue. can you take a look here -> https://react-pwa-dev.istackmanila.com/about

**Comment by jaysondaquer** [comment]
> did you installed any library after setup? If you used a library that uses window or document to function and the library is called in any child imports of server then we usually see a 500 server error.

we're not adding anything yet. we're just testing a fresh clone of the project. we're using nginx and pm2 to run the app.

**Comment by jaysondaquer** [comment]
![image](https://user-images.githubusercontent.com/7529733/32494086-3c07fadc-c3fb-11e7-9622-e08198c89cbf.png)
Additional updates @tirthbodawala

**Comment by tirthbodawala** [comment]
Ok. This is caused due to "getHeaders" function is not accessible from nodejs, also we are testing on ubuntu and everything works fine. Can you please share the nodejs version you are using ?

**Comment by tirthbodawala** [comment]
Ok. I see the following link for reference:
https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_headers_outgoingmessage_headernames

That is causing the issue. Let me check with latest version

**Comment by jhabdas** [comment]
Yep, can see `8.4.0` [codified](https://github.com/Atyantik/react-pwa/blob/master/package.json#L5-L7) in the package manifest right now. @jaysondaquer assuming you were not using a supported version of Node, were no warnings thrown when you built the app?

**Comment by stevenmatison** [comment]
I am seeing the same 500 error flash on a local version I am running as 'npm run build && node dist/server.js'  

There are no errors/warnings in console...  my versions are:
Stevens-MacBook-Pro:pwa stevenmatison$ npm -v
5.6.0
Stevens-MacBook-Pro:pwa stevenmatison$ node -v
v8.5.0

**Comment by tirthbodawala** [comment]
Hey @stevenmatison Can you please join our gitter channel? I think we can assist you more appropriately there.
