### ISSUE TITLE
What's your opinion with CSS-in-JS?

### ISSUE THREAD

**Issue by dav-is** [Atyantik/react-pwa#4]
I'm not saying this needs CSS-in-JS, but I'm interested in your thoughts concerning it. Maybe it would make for a nice addition?

**Comment by dav-is** [comment]
I’ve been keeping an eye on https://github.com/callstack/linaria

Thoughts?

**Comment by tirthbodawala** [comment]
@dav-is By CSS-in-JS i had the impression of using line-css with JS. By linaria we can write style and export it to external CSS files (which is very interesting). Are you looking for something like linaria ?

**Comment by dav-is** [comment]
That’s how CSS-in-JS is usally done, but I like the ideas in Linaria. Only downside is it isn’t very mature yet...

**Comment by tirthbodawala** [comment]
@dav-is I see your point. Let me have a through look at Linaria, If it helps in minimizing the page/head load will definitely give it a go.

**Comment by dav-is** [comment]
I gave this some more thought and I like our current implementation better.
