### ISSUE TITLE
React Native Hybrid

### ISSUE THREAD

**Issue by dav-is** [Atyantik/react-pwa#40]
Angular has https://ionicframework.com/
Where is React's hybrid app framework?

Can we support React Native?

Maybe we should consider a name change too? I've been working on a space/rocket themed site for the documentation too!

**Comment by tirthbodawala** [comment]
Well, I will have to dig the React Native, I am still digging core of React. Will definitely give it a look. My next target was to make the react-pwa plugable... like installable module, or like wordpress's plugin based. Wouldn't it be cool if everyone can develop their own plugin?

**Comment by dav-is** [comment]
It's still pretty rough, but here's what I've got so far with the updated documentation site. The stars in the background animate as well.

![Rough Site](https://user-images.githubusercontent.com/11590024/32567238-4f0dc88e-c480-11e7-8d26-fa678ad23d35.PNG)

**Comment by dav-is** [comment]
It's still pretty rough, but here's what I've got so far with the updated documentation site. The stars in the background animate as well.

![Rough Site](https://user-images.githubusercontent.com/11590024/32567238-4f0dc88e-c480-11e7-8d26-fa678ad23d35.PNG)

**Comment by dav-is** [comment]
It's still pretty rough, but here's what I've got so far with the updated documentation site. The stars in the background animate as well.

![Rough Site](https://user-images.githubusercontent.com/11590024/32567238-4f0dc88e-c480-11e7-8d26-fa678ad23d35.PNG)

**Comment by jhabdas** [comment]
Nice looking site @dav-is. It's very, uh, in tune with current geopolitical climate. 🤣

**Comment by tirthbodawala** [comment]
@dav-is this is pretty awesome. I am open to changes and would love to go in direction where its reqchable to more users and becomes more helpful.

**Comment by tirthbodawala** [comment]
@dav-is @jhabdas @ajay @yash name sugesstions?

**Comment by tirthbodawala** [comment]
Closing the discussion as we will move such talks to gitter or discord.
