### ISSUE TITLE
App doesn't start on windows machine with error (Cannot find module '../build/Release/sharp.node')

### ISSUE THREAD

**Issue by ArtemKha** [Atyantik/react-pwa#43]
After successful commands:
cd react-pwa && yarn install
yarn global add windows-build-tools
yarn global add node-gyp

I got the error after this: 
yarn start

....

ERROR in ./src/resources/images/mario-large.png?sizes=100w+200w+400w+800w&placeholder
Module build failed: Error: Cannot find module '../build/Release/sharp.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Artem\git\up\react-pwa\node_modules\sharp\lib\constructor.js:9:15)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Artem\git\up\react-pwa\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
 @ ./src/app/components/home/home.js 22:18-108
 @ ./src/pages/home.js
 @ ./src/routes.js
 @ ./src/core/client/dev.client.js
 @ multi babel-polyfill react-hot-loader/patch ./src/core/client/dev.client.js webpack-hot-middleware/client?name=common-client&path=/__hmr_update&timeout=2000&overlay=true

The command:

 node-gyp rebuild

gives me next result: 

gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\Artem\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Artem\\git\\up\\react-pwa\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Artem\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Artem\\.node-gyp\\8.9.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Artem\\.node-gyp\\8.9.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Artem\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Artem\\.node-gyp\\8.9.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Artem\\git\\up\\react-pwa',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Artem\\git\\up\\react-pwa\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: C:\Users\Artem\git\up\react-pwa) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Artem\AppData\Local\Yarn\config\global\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Artem\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Artem\git\up\react-pwa
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by tirthbodawala** [comment]
I think this refers to https://github.com/lovell/sharp/issues/669.
For Python related problem in windows there is a small guide at https://github.com/nodejs/node-gyp
May be path issue. Can you please check if the links mentioned solves you problem?

**Comment by ArtemKha** [comment]
Tried to do npm install instead of yarn and it worked

**Comment by tirthbodawala** [comment]
Thanks @ArtemKha. This will be added to docs as well.

**Comment by iamdarknight** [comment]
Facing similar issue. Using npm. Error is

> 

ERROR in ./src/resources/img/dog-cat.jpg?sizes=1200w+1000w+800w+600w+400w&placeholder                                                                                                            Module build failed (from ./node_modules/pwa-srcset-loader/index.js):                                                                                                                            Error: The specified module could not be found.                                                                                                                                                  \\?\C:\Users\Manaska\Applications\Clients\PAG\PAG-WS\react-pwa\node_modules\pwa-srcset-loader\node_modules\sharp\build\Release\sharp.node                                                            at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)                                                                                                                       at Module.load (internal/modules/cjs/loader.js:598:32)                                                                                                                                           at tryModuleLoad (internal/modules/cjs/loader.js:537:12)                                                                                                                                         at Function.Module._load (internal/modules/cjs/loader.js:529:3)                                                                                                                                  at Module.require (internal/modules/cjs/loader.js:636:17)                                                                                                                                        at require (internal/modules/cjs/helpers.js:20:18)                                                                                                                                               at Object.require (C:\Users\Manaska\Applications\Clients\PAG\PAG-WS\react-pwa\node_modules\pwa-srcset-loader\node_modules\sharp\lib/constructor.js:10:15)                                        at Module._compile (internal/modules/cjs/loader.js:688:30)                                                                                                                                       at Module._compile (C:\Users\Manaska\Applications\Clients\PAG\PAG-WS\react-pwa\node_modules\pirates\lib\index.js:83:24)                                                                          at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
--
