### ISSUE TITLE
add CDN urls

### ISSUE THREAD

**Issue by taqimustafa** [Atyantik/react-pwa#45]
@tirthbodawala just wanted to ask if there is any way we can add bootstrap CDN or googlemap script tag in the header ?

```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key="></script>

```

**Comment by tirthbodawala** [comment]
@taqimustafa You should not include scripts in head directly rather use loadScript in custom root component. You can have a look at example application with boilerplate. 

Also bootstrap is included, even if you are willing to include it from header from other cdn you should use the seo config in src/config/config.js as 

// src/config/config.js
```
{
  // ..other configs
  seo: {
    // ...other seo options
   links: [
     {
       rel: "stylesheet"
       href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
     }
   ]
  }
}
```
But the above method is highly discouraged as it would affect the offline availability of CSS

**Comment by taqimustafa** [comment]
@tirthbodawala thanks. Will try your solution. 👍

**Comment by RizwanZaheer** [comment]
How can I add dynamic script for different page for the SEO?
