### ISSUE TITLE
How to load fonts from resources/fonts directory?

### ISSUE THREAD

**Issue by lukaszzdanikowski** [Atyantik/react-pwa#46]
I would like to add custom font but it seems that font files are not loaded.
I've put my fonts into resources/fonts/abcd/abcd.eot
added this to my style.scss
```
@font-face {
  font-family: 'abcd';
  src: font-url(abcd/abcd.eot');
  font-weight: normal;
  font-stylle: normal;
}
html { font-family: abcd; }
```
Font is not loaded on dev and not copied to dist directory.

**Comment by tirthbodawala** [comment]
I think the path is incorrect.
```
@font-face {
  font-family: 'abcd';
  src: url('../fonts/abcd/abcd.eot')  format('embedded-opentype');
  font-weight: normal;
  font-style: normal;
}
html {font-family: abcd; }
```
Also the  compiled fonts are onlu viewable on building the application, i.e. after running `npm run build`

**Comment by tirthbodawala** [comment]
@lukaszzdanikowski were you able to solve the issue with the answer above?

**Comment by lukaszzdanikowski** [comment]
@tirthbodawala yep, that works perfectly.

**Comment by tirthbodawala** [comment]
@lukaszzdanikowski thanks for replying. Closing the issue now :)
