### ISSUE TITLE
Error in Build regarding router-loader

### ISSUE THREAD

**Issue by bytewiz** [Atyantik/react-pwa#49]
After following the instructions for routing from the documentation, and running the build script it errors out with the below:

```
ERROR in ./pages/container.js
Module build failed: TypeError: Cannot read property 'length' of null
    at Object.module.exports (.../loaders/route-loader.js:8:7)
```

### Note:
For the route itself I am wrapping the component in a container using `connect()` from `react-redux` but shouldn't kill the routing?

`./src/routes.js`
![image](https://user-images.githubusercontent.com/16811871/33156058-3cd5d04a-cff6-11e7-8360-7f20f4cead93.png)

`./src/pages/index.js`
![image](https://user-images.githubusercontent.com/16811871/33156070-67666b12-cff6-11e7-8460-07e6916d5f52.png)

And here `Component` is simply pointing to a container component like:
```
import Component from './component'

function mapStateToProps() {
// some mapping here..
} 

export default connect(mapStateToProps)(Component)
```

Let me know if additional info is required :v:

**Comment by tirthbodawala** [comment]
@bytewiz, the pages folder should be used to only define files with routes, its very necesaary because route loader tries to add magic in every file inside pages folder, as you have added Compnent inside pages folder, its breaking the code, try moving Component to app folder and it should work just fine.

Let me know if this helps!

**Comment by bytewiz** [comment]
@tirthbodawala thanks, that seemed to work out but ran into another problem loading an image and the weird thing is I am loading in an image from the same location that works.

this is the error

```
ERROR in ./assets/img/coverphoto.jpg
Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/nielshansen/Documents/external-event-website/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found

    at Promise.all.then.arr (/Users/nielshansen/Documents/external-event-website/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./app/eventWebsite/Hero/index.js 23:18-63
 @ ./app/eventWebsite/index.js
 @ ./app/container.js
 @ ./pages/index.js
```

**Comment by tirthbodawala** [comment]
@bytewiz Can you please share the code of `/app/eventWebsite/Hero/index.js` ?

**Comment by tirthbodawala** [comment]
Also to solve the error for `dyld: Library not loaded` Please make sure you have *libpng* installed:

Ubuntu: 
`sudo apt-get install libpng-dev`

Mac (with brew)
`brew install libpng`

**Comment by bytewiz** [comment]
Let me try that and additionally:

Loading the image from `./src/app/eventWebsite/Hero/index.js`
and the image is used in the same file like this: 
```
backgroundImage: linear-gradient(to bottom, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url(${DefaultHeroImg}),
```
like so: `import DefaultHeroImg from '../../../assets/img/coverphoto.jpg';`
and `assets` is found in `./src/assets/img/coverphoto.jpg`

**Comment by bytewiz** [comment]
@tirthbodawala That worked 👍  Now only problem I am left with is 
```
ERROR in server.js from UglifyJs
    Unexpected character '`' [server.js:109,84956]
```

But let me see if I can solve that :v:

**Comment by tirthbodawala** [comment]
Please move the `require("../styles/fonts.css")` from routes to `src/client.js`
As styles need to be managed via client it would make more sense and won't hinder compilation of server.js

**Comment by bytewiz** [comment]
@tirthbodawala I moved `require("../styles/fonts.css")` to the component instead but I am still getting the same UglifyJS error 😞

**Comment by tirthbodawala** [comment]
@bytewiz Is there a way I can assist you remotely? you can reach me at tirthbodawala [at] atyantik.com

**Comment by bytewiz** [comment]
@tirthbodawala I can't share the code, but let me try to reproduce it with another example :v: then I will share that

**Comment by tirthbodawala** [comment]
@bytewiz I just create a gitter channel for react-pwa if you wish to join:
https://gitter.im/react-pwa/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
