### ISSUE TITLE
CSP Support

### ISSUE THREAD

**Issue by dav-is** [Atyantik/react-pwa#5]
I'm a strong advocate of [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). I think it'd a great idea to implement it.

**Comment by dav-is** [comment]
I took a quick look at this last night and discovered the code uses quite a bit of unsafe `eval()`. This needs to be done differently as it allows for xss attacks.

**Comment by tirthbodawala** [comment]
@dav-is are you worries about ‘eval require dev.server’? cause that is nothing to worry about its just a patch for prod server to not inlice dev.server.js in build.

**Comment by dav-is** [comment]
No I think it’s something one of the dependencies does on build. If you search “eval” inside the bundle.js, you will see what I mean. There’s several lines of eval at the very end.

**Comment by dav-is** [comment]
An explaination of why eval shouldn’t be used: https://stackoverflow.com/questions/37155270/content-security-policy-csp-safe-usage-of-unsafe-eval

**Comment by dav-is** [comment]
Actually, I think what I said only happens during development mode... a bit inconvenient for testing the headers

**Comment by dav-is** [comment]
I can't seem to get a production build to work with: https://www.npmjs.com/package/express-csp-header

It throws an error no matter what I try...

```
ERROR in server.js from UglifyJs
    Unexpected token: name (cspString) [server.js:56441,5]
```

**Comment by jhabdas** [comment]
Advise against getting too far down the InfoSec here's how you should do your security hole with boilerplates. And I always say the same for auth as both are very opinionated things and adding security features may give individuals a false sense they're, ahem, covered when it comes to their node deps.

Adding [Snyk](https://snyk.io/) should be a good enough way to provide a baseline of security for the app itself. And knowledge of and implementation of [`rel=noopener`](https://mathiasbynens.github.io/rel-noopener/) in case of `Link` component with `target` attribute would be something worth sliding into the generator if it makes sense.

**Sidebar:** Snyk has caught a literal boatload of DoS and other kinds of easy attack vectors in my [RN boilerplate](https://github.com/jhabdas/react-native-webpack-starter-kit/blob/master/.snyk).

Do like where @dav-is head is at. Might be worth a call out in the readme or Wiki to help educate consumers.

**Comment by dav-is** [comment]
Never thought of adding rel=noopener to the Link component. Nice thinking

**Comment by tirthbodawala** [comment]
Ok. I have added support for CSP, but leaving the control in hands of user/developer and it might vary according to env where the app is running:

Editing **src/config/config.js** as below will do the job
```
{
  // ... other config params
  seo: {
    // ...
    meta: [
      // ....
      {
        "httpEquiv": "Content-Security-Policy",
        "content": "default-src 'self'; img-src https://*; child-src 'none';"
      }
    ]
  }
  // ... other config params
}
```

**Comment by dav-is** [comment]
Do you provide secure defaults? Have you tested the config? In development mode, unsave-eval is used so it may cause errors.
