### ISSUE TITLE
Using json files from public directory

### ISSUE THREAD

**Issue by lukaszzdanikowski** [Atyantik/react-pwa#52]
With latest code from master when i create simple test.json in public direcory:
```
[{
  "id": 1,
  "text": "test1"
}, {
  "id": 2,
  "text": "test2"
}]
```
and want to load it in lets say home page with:
```
preLoadData: async ({ api, host }) => {
      return api.fetch(host + "/test.json", { swcache: 20000 });
    },
```
in development mode everything works ok, but when i run prod version i'm getting
```
sw.js:26 Uncaught (in promise) Error: An error was thrown by workbox with error code: ;'request-not-cached' with extras: '{"url":"file:///___MY_PROJECT_PATH___/dist/public/build/client.6e57f4686541547d986a.bundle.js","error":{}}'
```
I know that error comes from SSR that has issues with accessing file but how to handle that situation?
Another small issue is that the host variable that is provided to preLoadData is not realy a host  (in the WebAPI Location object meaning) at least on the server side cause it also has protocol part.

**Comment by tirthbodawala** [comment]
@lukaszzdanikowski I tried replicating the bug, but it worked perfectly.
Here is what I did in the repo to replicate it:
1) Created test.json in src/public/test.json with data:
```
[{
  "id": 1,
  "text": "test1"
}, {
  "id": 2,
  "text": "test2"
}]
```
2) Edited src/pages/blog.js to look as below:
```
const routes = [
  {
    path: "/blog",
    exact: true,
    layout: DefaultLayout,
    component: BlogListing,
    preLoadData: async ({ api, host }) => {


      //// ---->>> Test code in preLoadData <<<----
      console.log(await api.fetch(`${host}/test.json`));
      //// ---->>> Test code in preLoadData <<<----

      return api.fetch("https://www.atyantik.com/wp-json/wp/v2/posts", { swcache: 20000 });
    },
  },
  {
    path: "/blog/:id",
    layout: DefaultLayout,
    component: BlogPost,
    preLoadData: async ({match, api}) => {
      const { params } = match;
      return api.fetch(`https://www.atyantik.com/wp-json/wp/v2/posts/${params.id}`, { swcache: 20000 });
    },
  }
];

export default routes;
```
3) Ran it in development mode and got the output as expected 
```
// npm start
[{"id":1,"text":"test1"},{"id":2,"text":"test2"}]
```

4) Ran it in production mode and got the same output
```
// npm run build && node dist/server.js
[{"id":1,"text":"test1"},{"id":2,"text":"test2"}]
```

Did I missed anything?

**Comment by tirthbodawala** [comment]
@lukaszzdanikowski any updates?

**Comment by lukaszzdanikowski** [comment]
@tirthbodawala If you go through home, so first localhost:3003/ then click blog in navigation everything is ok, but if go directly to localhost:3003/blog you should be able to see this error in the console.

**Comment by tirthbodawala** [comment]
![working json file](https://user-images.githubusercontent.com/11286271/33703834-d233d736-db4f-11e7-8b84-20300d971290.png)
@lukaszzdanikowski I tried it on my machine, unable to replicate it. Can you please provide more details?

**Comment by lukaszzdanikowski** [comment]
@tirthbodawala sorry it must have been some weird dependency issue cause when i removed ```node_modules``` and run ```npm install``` once again the error doesn't occur any more.

**Comment by tirthbodawala** [comment]
@lukaszzdanikowski No problem, am glad the issue is solved.
