### ISSUE TITLE
Internal Server Issue 

### ISSUE THREAD

**Issue by RizwanZaheer** [Atyantik/react-pwa#56]
I already resolve the window & navigator(#55) issue 
Project is successfully build with no error "node dist/server.js" is also run successfully with no error 
but when I'm going to access in browser then I'm getting  " 500 Server error occurred"

Error: Minified React error #149; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=149&args[]=carouselWrapper for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by tirthbodawala** [comment]
Well are you using multiple react version? is carouselWrapper a plugin or npm package?

**Comment by dav-is** [comment]
I ran into the same error. Refs cannot be defined by strings. 

Use this notation:
```
<Element ref={(el) => {this.el = el;}} />
```

**Comment by tirthbodawala** [comment]
@RizwanZaheer Does the solution provided by @dav-is solves your aissue?

**Comment by tirthbodawala** [comment]
Closing due to no-reply.

**Comment by RizwanZaheer** [comment]
@tirthbodawala No, I'm using single verison of react.
carouselWrapper is a simple class defined in this project for carousel
In Dev mode It's work fine but this issue came in production build

**Comment by tirthbodawala** [comment]
@RizwanZaheer  Have you upgraded to latest version of react-pwa boilerplate? its using pawjs.

**Comment by RizwanZaheer** [comment]
Yes, now it's working fine

**Comment by tirthbodawala** [comment]
Cool. thanks for informing :+1:
