### ISSUE TITLE
Need working sample action/reducer from within /src/app/component

### ISSUE THREAD

**Issue by stevenmatison** [Atyantik/react-pwa#58]
Hi,  I am working with this boilerplate and struggling to get an action/reducer working for a userProfile component.   The best I can get so far is setting my initial state with default data.  These defaults are persisting after the actions complete.  When executing the action (includes an api call to get the real userProfile data) I can see the data response and see it pass through my reducer and the lodash assign but it is not replacing the initial state when state is connected in a separate component.     

I would like to see a basic working sample inside of a /src/app/component/ that works with the global state.   The only action/reducer that appears to be part of react-pwa is in the fileset as /core/src/app/component/screen.

 Thanks,  

Steven

**Comment by tirthbodawala** [comment]
Hi @stevenmatison I will definitely send you a working example of redux, will add an example in boilerplate. Thanks for your patience.

**Comment by stevenmatison** [comment]
Thank you.  With the working userProfile we should be pushing this out into production in January.

 I really appreciate all your hard work on this boilerplate.

**Comment by tirthbodawala** [comment]
Thanks @stevenmatison We are loving it when we see it in action, Do share the URL of production will include in README.md win-win :+1:

**Comment by stevenmatison** [comment]
I will delete these later but:  

https://stevenm.cogobox.com:3003/?id=701
https://stevenm.cogobox.com:3003/?email=steven@sceneserver.net
https://stevenm.cogobox.com:3003/?phone=13218484926
https://stevenm.cogobox.com:3003/?mac=F4:5C:89:99:35:F9

this is running "npm start" as such much of the pwa basics are not operating.   I have discovered that when I do 'npm run build && node dist/server.js' that styling is blown away with some giant padding around the Dom body

**Comment by tirthbodawala** [comment]
@stevenmatison Please join us on Gitter:
https://gitter.im/react-pwa/Lobby We can definitely assist more with chat :)

**Comment by yash-thakur** [comment]
#60 I have added the redux example you can have a look at it.

**Comment by stevenmatison** [comment]
Thank you so much!!
