### ISSUE TITLE
Failure to Compile on `npm start`

### ISSUE THREAD

**Issue by lnorton89** [Atyantik/react-pwa#59]
Running `npm start` throws several failure to compile errors. Accessing localhost:3003 shows blank page with the title "Common Title". 

[npm_start.log](https://github.com/Atyantik/react-pwa/files/1576310/npm_start.log)

Node: 9.2.1 
NPM: 5.60
Ubuntu 16.04

**Comment by tirthbodawala** [comment]
@lnorton89 Its mostly caused due to incomplete download of node-sass
Try
```
rm -rf node_modules
npm i
```

That should solve it.

**Comment by tirthbodawala** [comment]
Sure will update docs for build essentials and node-gyp. Thanks for mentioning. Will take care of it.
