### ISSUE TITLE
HSTS Support

### ISSUE THREAD

**Issue by dav-is** [Atyantik/react-pwa#6]
I think [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) headers should be added by deafult when using `now`. They should be opt in (in production mode) otherwise.

**Comment by tirthbodawala** [comment]
Hey @dav-is. thanks for the reference to hsts. We have enabled it by default for HTTPS sites. If some one does not indent to turn it on for some reason, we have added it to config file.

```
...
hsts: {
    enabled: true,
    // mageAge: Must be at least 18 weeks to be approved by Google, but we are setting it to 1 year
    maxAge: 31536000,
    // Must be enabled to be approved by Google
    includeSubDomains: true,
    preload: false,
},
...

```
