### ISSUE TITLE
Issue with imagemin-mozjpeg

### ISSUE THREAD

**Issue by ezwon** [Atyantik/react-pwa#63]
forgot the link that says its better to use `imagemin-jpegtran` instead.

on Mac, node v8.9.3

> mozjpeg@4.1.1 postinstall /Users/jaysondaquer/work/repos/github/react-pwa/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/Users/jaysondaquer/work/repos/github/react-pwa/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/jaysondaquer/work/repos/github/react-pwa/node_modules/mozjpeg/vendor" --bindir="/Users/jaysondaquer/work/repos/github/react-pwa/node_modules/mozjpeg/vendor" --libdir="/Users/jaysondaquer/work/repos/github/react-pwa/node_modules/mozjpeg/vendor" && make --jobs=8 && make install --jobs=8
Command failed: autoreconf -fiv
/bin/sh: autoreconf: command not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by tirthbodawala** [comment]
@ezwon I researched and experimented a bit with jpegtran it has same issues as above as both are using cjpeg to function. 

Why don't you try this?

Linux:
```
sudo apt-get install libtool automake autoconf nasm
```  

OS X:
```
brew install libtool automake autoconf nasm
```
