### ISSUE TITLE
Server state, client state and component state of redux? How does it work?

### ISSUE THREAD

**Issue by rperrote** [Atyantik/react-pwa#65]
Reviewing the project I can see 3 definitions of the state of redux.. I assign different initialState in the 3 places and deploy the app:

1. for few secons i can see a server initial state
2. then the state changes for the client version of initial state
3. I never see the initial state of the component

How does it work?

I need it to work offline. That the user can add the app to his home and when he opens the app he sees his state cached and that it is validated with the one he has in the server and is updated on both sides. (merge status)

PD: Sorry for my bad english translate with google :P

Best regards, Rodrigo Perrote.

**Comment by tirthbodawala** [comment]
@rperrote. Well as its SSR supported application we need initial state in server.js and client.js. No other file needs to be updated. 

`src/client.js`
```
export const reduxInitialState = {};
```

`src/server.js`
```
app.use((req, res, next) => {
  res.locals.reduxInitialState = {};
  next();
});
```

I need to understand your exact requirement how you need to sync it with the server and work with the offline state. Can you please explain more?

**Comment by tirthbodawala** [comment]
Closing due to no-reply.
