### ISSUE TITLE
api.fetch method, only accepts json responses?

### ISSUE THREAD

**Issue by migueloop** [Atyantik/react-pwa#66]
Hello, 

I've been using api.fetch in a page to get data but having a look to the class it's not possible to get other data than a json response from the server, right?

If we use another lib, we will loose state management done in this pawjs/src/libs/api/api.js file, right?

**Comment by tirthbodawala** [comment]
@migueloop Well yes you are right, the default we are using is "universal-fetch" and "api" library we created is tightly bound to it. 

But you can directly use "universal-fetch" for other responses.
 ```language-js
import fetch from "universal-fetch";

fetch("https://someapi.com/xml-endpoint", {})
   .then()
   .catch()
```

The package usage can be found here: https://github.com/Pitzcarraldo/universal-fetch

But now as you raised this question It got me thinking if we can customize the API library for other responses as XML, HTML etc. What are you exactly looking for?

**Comment by migueloop** [comment]
I was getting HTML response. Since server is also mine, I just changed to a json response, but could be nice to have other response types.

**Comment by migueloop** [comment]
I will try to make a pull request just changing this fact. Should we use a different library like axios or request?

**Comment by tirthbodawala** [comment]
Well @migueloop I was more aligned to ES6 fetch "whatwg-fetch" with new html5 and thus included it. We can definitely try installing other options but would like to research properly.
