### ISSUE TITLE
Using Hapijs

### ISSUE THREAD

**Issue by TheForgotten69** [Atyantik/react-pwa#68]
Hey there!

Love this project, but just want to know, want do I need to change if I want to use Hapi rather than express?

**Comment by tirthbodawala** [comment]
@TheForgotten69 You want to change from express to hapi for API or Universal Routing?

**Comment by tirthbodawala** [comment]
Closing issue due to re-reply.

**Comment by TheForgotten69** [comment]
Fo universal routing, it's what work best for me.
