### ISSUE TITLE
Implementing Material UI

### ISSUE THREAD

**Issue by susan8098** [Atyantik/react-pwa#69]
Hi, wondering how I can implement Material UI with this boilerplate? According to Material UI Doc, I'd have to insert <MuiThemeProvider> somewhere in the root file to wrap around React App element, where can I do this?

**Comment by tirthbodawala** [comment]
Hey @susan8098 apologise for late reply. Please share the Material UI link you want to use I shall create an example of usage for it.

**Comment by susan8098** [comment]
Hey @tirthbodawala, thanks for getting back, here's the doc link:
http://www.material-ui.com/#/get-started/usage

**Comment by susan8098** [comment]
Any luck at all @tirthbodawala?

**Comment by yash-thakur** [comment]
@susan8098  Here goes the solution implemented and tested.
Make a new file `src/app/components/root/index.js`
with the content as follows:
``` javascript
import React, { Component } from "react";
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';

export default class AppRoot extends Component {
  render() {
    return (
      <MuiThemeProvider>
        {this.props.children || null}
      </MuiThemeProvider>
    );
  }
}
```

Now go to `src/config/classMap.js`
replace `
import Root from "pawjs/src/components/root";` with the path of the newly created root file. Here it will be `import Root from "../app/components/root/index";`

**Comment by ivoreis** [comment]
Hi @yash-thakur @tirthbodawala, the current solution for material-ui works but only for the default case, I believe SSR is still an issue.

From the official documentation:
https://material-ui-1dab0.firebaseapp.com/guides/server-rendering/#handling-the-request

In order to make material-ui fully work with SSR  and avoid FOUC the styles need to be extracted and injected into the HTML. 

```js
  // Render the component to a string.
  const html = renderToString(
    <JssProvider registry={sheetsRegistry} generateClassName={generateClassName}>
      <MuiThemeProvider theme={theme} sheetsManager={new Map()}>
        <App />
      </MuiThemeProvider>
    </JssProvider>
  )

  // Grab the CSS from our sheetsRegistry.
  const css = sheetsRegistry.toString()

  // Send the rendered page back to the client.
  res.send(renderFullPage(html, css))
```

Is there an easy way of doing this? 

Thanks

**Comment by cazetto** [comment]
Hi there! I have the same need to implement the material-ui.

Has anyone found a solution? @ivoreis @yash-thakur @tirthbodawala 

Thanks
