### ISSUE TITLE
Progressive Image loading

### ISSUE THREAD

**Issue by dav-is** [Atyantik/react-pwa#7]
I think this would be a useful feature if implemented correctly.

See: https://jmperezperez.com/medium-image-progressive-loading-placeholder/
https://medium.com/@evenchange4/reproducing-medium-style-progressive-image-loading-for-react-2e83bba0c608

**Comment by tirthbodawala** [comment]
Hi @dav-is 
Checkout the https://react-pwa.now.sh for example of Progressive Image loading.
We have already implemented this feature. We have written an extended version of [srcset-loader](https://github.com/timse/srcset-loader)

We support WebP format as well. 
We can also add lazy loading, but I shall leave it for user to decide or we can add it to other milestone.

**Comment by dav-is** [comment]
Truly impressive!
