### ISSUE TITLE
Error: Cannot find module './components/counter/reducer

### ISSUE THREAD

**Issue by attilavago** [Atyantik/react-pwa#72]
Following your setup instructions for a clean app results in an error. Tried twice... :/

`Error: Cannot find module './components/counter/reducer'`

**Comment by tirthbodawala** [comment]
@attilavago Can you please share the whole error log? or the console with line to line description please? 
I will look into it asap.

**Comment by yash-thakur** [comment]
@attilavago The simplest way to solve this error would be to empty `src/app/reducers.js` file for now.

To completely clean the project follow these steps below.
1) Delete the reducer file `src/app/reducers.js`.
2) Remove this code from client.js. 
```javascript
// ...other imports
import * as appReducers from "./app/reducers";

export const reduxInitialState = {
  counter: {
    count: 5
  }
};
export const reduxReducers = appReducers;
// ...
```

3) Remove this from server.js.
```javascript
// ...other imports
import * as appReducers from "./app/reducers";

// ...
/**
 * --- Your custom code START ---
 */
app.use((req, res, next) => {
  res.locals.reduxInitialState = {
    counter: {
      count: 5
    }
  };
  res.locals.reduxReducers = appReducers;
  next();
});

/**
 * --- Your custom code END ---
 */
 // ...
```

And the boilerplate is clean of any unnecessary code
