### ISSUE TITLE
Production Mode Build Error

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [Atyantik/react-pwa#73]
I tried to test pwa locally in production mode.
Used: NODE_ENV=production npm start command but getting error below-

/Users/veteran/Desktop/Spinfluence/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/veteran/Desktop/Spinfluence/src/resources/images/pwa/icon-72x72.png: Unexpected character '�' (1:0)

Please help me, how can I resolve this?

**Comment by tirthbodawala** [comment]
You cannot start in production mode. You can only build in production mode as of now.
`NODE_ENV=production npm run build`

We are not supporting production start at the moment.
