### ISSUE TITLE
How can I use FCM?

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [Atyantik/react-pwa#74]
I tried to use firebase cloud messaging inside pwa, but when I request to get FCM token, getting error below ;

FirebaseError {code: "messaging/failed-serviceworker-registration", message: "Messaging: We are unable to register the default s…). (messaging/failed-serviceworker-registration).", browserErrorMessage: "Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').", stack: "FirebaseError: Messaging: We are unable to registe…ebpack-internal:///937:262:39)↵    at <anonymous>"}

Maybe FCM only works in production mode?

**Comment by tirthbodawala** [comment]
How are you trying to work with FCM ? Can you share the code example you are trying to implement?

**Comment by ThunderBoltEngineer** [comment]
-I wrote below code in login.js, which is login screen.  Works well. Permission granted.

// configure firebase 
firebase.initializeApp(firebaseConfig);
const messaging = firebase.messaging();

componentDidMount() {
...
messaging.requestPermission()
            .then(function() {
                  console.log('Notification Permission Granted');
            })
            .catch(function(err) {
                  console.log('Unabled to get permission to notify ' + err);
            });
}

-On main.js, which is home screen, I added this code;
...
componentDidMount() {
...
firebase.messaging().getToken().then(function(currentToken) {
				console.log(currentToken);
			});

Causes error.
FirebaseError {code: "messaging/failed-serviceworker-registration", message: "Messaging: We are unable to register the default s…). (messaging/failed-serviceworker-registration).", browserErrorMessage: "Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').", stack: "FirebaseError: Messaging: We are unable to registe…ebpack-internal:///937:262:39)↵    at <anonymous>"}
browserErrorMessage
:
"Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html')."
code
:
"messaging/failed-serviceworker-registration"
message
:
"Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html'). (messaging/failed-serviceworker-registration)."
stack
:
"FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html'). (messaging/failed-serviceworker-registration).↵    at eval (webpack-internal:///937:262:39)↵    at <anonymous>

**Comment by tirthbodawala** [comment]
Ok. I am no expert in FCM but let me try to help you with proper Initializations here.
1) Any Initialization that is only client specific and does not require SSR should be in `src/client.js`

So the following code should be in client.js
```
firebase.initializeApp(firebaseConfig);
const messaging = firebase.messaging();
``` 

I see the error above is pointing to webpack-internal which is webpack-dev-server and used when server is executed. Shifting the above code would help. Let me know if that solves the issue.

**Comment by ThunderBoltEngineer** [comment]
I moved the code into client.js, but still getting firebase error.
"Failed to register a service worker ..."

:(

**Comment by ThunderBoltEngineer** [comment]
Any solution for this issue ?   x(

**Comment by johnnybossboy** [comment]
Any solution? I have the same problem

**Comment by tirthbodawala** [comment]
@johnnybossboy We re in process of developing a firebase plugin for the same. Let me re-open the issue and shall close it as soon as the plugin is available.

**Comment by tirthbodawala** [comment]
@ThunderBoltEngineer were you able to find a solution to your problem as well?

**Comment by ThunderBoltEngineer** [comment]
Nope.  I had to use create-react-app.

**Comment by tirthbodawala** [comment]
@ThunderBoltEngineer Apologies. I will jump on it asap.

**Comment by jld3103** [comment]
I tried do do it the normal way as described in the official documentation and I got it to work.
I don't know where your problems are...

**Comment by jld3103** [comment]
I looked again at your error and I know what it is:
react-pwa doesn't let you serve your own service worker (that's why you get the MIME type error).
FIX:
I used my web server to handle this special file.

**Comment by jld3103** [comment]
See [here](https://github.com/Atyantik/react-pwa/issues/111#issuecomment-432119172) how to fix this issue.
