### ISSUE TITLE
Production Error

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [Atyantik/react-pwa#75]
I am currently using React-Slick component and it is raising error in production mode.
"matchMedia not present, legacy browsers require a polyfill", I am getting this error message when I try to run  "NODE_ENV=production node server.js"  in /dist directory.

Please help me fix this issue.

**Comment by tirthbodawala** [comment]
Ok. @ThunderBoltEngineer so I think you are using a library that requires window & document to function. further. Well if you are looking for SSR solution we propose you use plugins that are SSR compatible. 

https://github.com/akiran/react-slick/pull/950

Well, there is always a work around for such plugins. I will try to explain an example here:

Let me call it ComponentX (ReactSlick) that utilizes a non-SSR library like ReactSlick

I shall create a folder in `src/app/components/ComponentX`
and thus create following files:
1) `src/app/components/ComponentX/package.json`
2) `src/app/components/ComponentX/server.js`
3) `src/app/components/ComponentX/client.json`

Content of `src/app/components/ComponentX/package.json` should be as follows:
```language-json
{
  "private": true,
  "name": "ComponentX",
  "main": "./server.js",
  "browser": "./client.js"
}
```

Content of `src/app/components/ComponentX/server.js` (Depends on the usage though)
Saying do not render anything during server-side rendering.
```language-js
export default () => {
   return null;
} 
```

Content of `src/app/components/ComponentX/client.js` (Again - depends on the usage though)  
```language-js
export * from "react-slick"; 
```


Now in the component using React-Slick you can change it like:

`src/app/components/Home/index.js`
```language-js
import Slider from "../ComponentX"
export default class Home extends React.Component {
   render() {
       <div>
           <p> this is home page with slider below</p>
           <Slider props="" otherprops="">
               <img src="2.jpg" />
               <img src="2.jpg" />
               <img src="2.jpg" />
           </Slider>
       </div>
       
   }
}
```
