### ISSUE TITLE
reac

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [Atyantik/react-pwa#77]
Hi , I am using react-router(4.2.0) inside my project and it is working well in development mode.
But when I try on production mode, it just doesn't work.
At the point of redirection, site url changes but page content is never updated.
It seems component is not rendered for the new url. 
Tried navigating to other pages, but all same. 

Please let me know how I can resolve this issue.

**Comment by dav-is** [comment]
Thank you for the 5 emails I received from this issue all at once.

**Comment by ThunderBoltEngineer** [comment]
Sorry, I made mistake.   Anyway, please collaborate on this issue.

**Comment by dav-is** [comment]
Console errors anywhere?

**Comment by ThunderBoltEngineer** [comment]
No console errors...
