### ISSUE TITLE
React-router not working in production mode

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [Atyantik/react-pwa#78]
I'm re-posting this issue because there weren't enough comments on the first one.

After fetching data from server, app should navigate to next page - this works well on development mode.
But in production mode, after fetching data, url just changes (from localhost:3003/login  to localhost:3003/main) but main component is never loaded and just login page is still rendered).
In login component, I used "this.props.history.push()" for navigation.

I couldn't find out solution, please help me.

**Comment by ThunderBoltEngineer** [comment]
No way to resolve this issue?

**Comment by yash-thakur** [comment]
```javascript
import {connect} from "react-redux";
import {push} from "react-router-redux";

@connect()
export default class YourClassName extends React.Component{
      //This will push the state to react-router
      this.props.dispatch(push("search"));
}
```

I hope this helps.

**Comment by ThunderBoltEngineer** [comment]
Thank you, but can I use @connect in this boilerplate?

**Comment by yash-thakur** [comment]
Yes for sure @ThunderBoltEngineer

**Comment by ThunderBoltEngineer** [comment]
As you know, we should wrap react app component with 'Provider'.
Where should I put that?

**Comment by yash-thakur** [comment]
For wrapping component refer to this issue: #69

**Comment by ThunderBoltEngineer** [comment]
@yash-thakur ,  I have followed the issue 69, but now app renders nothing.
