### ISSUE TITLE
Allow async redux initial state

### ISSUE THREAD

**Issue by vishalgheravada** [Atyantik/react-pwa#79]
right now redux initial state can be set by `export const reduxInitialState` but I have a request to fulfil where redux initial state can be decided after an Ajax request only. Is there a way to do it?
if not I would rather suggest following solution:
```language-js
export const reduxInitialState = async() => {
   const data = await someAsyncFunction();
   return {
       some: "staticData",
       dynamic: data 
   };
}
```

And where ever the function is utilised it can be awaited!

**Comment by IrvingAxelB** [comment]
Hello, 

I am trying to use async actions, but I am stuck on how to make it work on this project. 

Any help or guidance would be greatly appreciated!

**Comment by tirthbodawala** [comment]
@IrvingAxelB We are working on integrating Redux-Thunk. that should allow that. will integrate it in next release

**Comment by IrvingAxelB** [comment]
@tirthbodawala Thank you for the quick response! When is the next release scheduled to come out?

**Comment by tirthbodawala** [comment]
@IrvingAxelB We are planning a rewrite of the react-pwa with webpack4 which is very fast along with optimizations and implementation of redux-thunk. We are planning to launch it before 1st April 2018

**Comment by MikeShobe** [comment]
When is the new release date for this v2?

**Comment by tirthbodawala** [comment]
@MikeShobe the release date is targeted for version 2 is end of June.

**Comment by denny64** [comment]
@tirthbodawala Any updates on this?

**Comment by jibay** [comment]
hello,

You can use Redux-Thunk in client.js like this:

`
import * as appReducers from "./app/reducers";
import thunk from "redux-thunk";


export const reduxInitialState = {
  counter: {
    count: 15
  }
};
export const reduxReducers = appReducers;

export const reduxMiddlewares = [
  thunk,
];

if (module.hot) module.hot.accept();

`
