### ISSUE TITLE
Workbox.js

### ISSUE THREAD

**Issue by dav-is** [Atyantik/react-pwa#8]
It appears you are using custom service worker code? Maybe using [workbox.js](workboxjs.org) would make for a longer term solution as it is being actively maintained, so you wouldn't need to worry about it.

Also, don't take my many issues I've opened as disrespect. I appreciate the work you've done and think you've done a much better job than a lot of the other boilerplates.

Thanks, 
Davis

**Comment by tirthbodawala** [comment]
@dav-is I don't know if you understand, but your contribution is In-Valuable to the project. Informing about improvements is something we really really appreciate. Your name has been echoing in the office from past 2 days. 
You are the Hero of knowledge @ Atyantik :)  Please keep up the great contribution.

**Comment by tirthbodawala** [comment]
@dav-is We have used our custom logic as we are proving more functionality than workbox.js at the moment, which include local caching, custom API request caching. I think we can find a workaround to include workbox.js in upcoming milestones. but as of now as I go through their documentation we have covered most of the part.

**Comment by tirthbodawala** [comment]
@dav-is We have implemented workbox-sw but as a lib in core. We were unable to make it functional via 
`yarn add` due to the following issue
https://github.com/GoogleChrome/workbox/issues/352

But once its solved we shall move it to node_modules again.
