### ISSUE TITLE
Listening at http://0.0.0.0:3003 is wrong

### ISSUE THREAD

**Issue by scoutrul** [Atyantik/react-pwa#80]
While `npm start` 

> Creating bundle with Webpack dev server.. Please wait..
Listening at http://0.0.0.0:3003
And nothing happens.

But actual address is http://localhost:3003

**Comment by yash-thakur** [comment]
0.0.0.0 is also know as localhost

**Comment by androidfanatic** [comment]
0.0.0.0 isn't also known as localhost though. 0.0.0.0 binds to all interfaces which may or may not be dangerous at times but is anyways used in the industry and widely accepted.
