### ISSUE TITLE
Favicon issue

### ISSUE THREAD

**Issue by RizwanZaheer** [Atyantik/react-pwa#81]
When first time Site is bootup then favicon is work fine but navigate to different url then it's not working properly.
@tirthbodawala  have you checked this issue?

**Comment by tirthbodawala** [comment]
@RizwanZaheer Checking this right now. I see the issue here... Thanks for reporting.

**Comment by RizwanZaheer** [comment]
Thanks @tirthbodawala ,
Let me know when you fix this bug :)

**Comment by tirthbodawala** [comment]
@RizwanZaheer This bug has been solved with the implementation of PawJS v2. Unfortunately, it is a major change and would require upgrading a lot, but upgrading to PawJS v2 is recommended for more performance.

**Comment by RizwanZaheer** [comment]
Thanks @tirthbodawala 
can you please share the migration steps for us.
