### ISSUE TITLE
Error npm i

### ISSUE THREAD

**Issue by devalexandre** [Atyantik/react-pwa#85]
node : v9.7.1
npm : 5.6.0

error:

> sharp@0.18.4 install /home/alexandre/projetos/react-pwa/node_modules/sharp
> node-gyp rebuild

make: Entering directory '/home/alexandre/projetos/react-pwa/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
make: g++: Comando não encontrado
sharp.target.mk:119: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 127
make: Leaving directory '/home/alexandre/projetos/react-pwa/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/alexandre/.nvm/versions/node/v9.7.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/home/alexandre/.nvm/versions/node/v9.7.1/bin/node" "/home/alexandre/.nvm/versions/node/v9.7.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/alexandre/projetos/react-pwa/node_modules/sharp
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-shallow-testutils@2.0.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-shallow-testutils@2.0.0 requires a peer of react-addons-test-utils@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-test-render@1.1.1 requires a peer of react@15.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-test-render@1.1.1 requires a peer of react-addons-test-utils@15.x.x but none is installed. You must install peer dependencies yourself.
npm WARN ReactPWA@0.2.8 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tirthbodawala** [comment]
The issue is related to spark package: Please refer the issue [https://github.com/lovell/sharp/issues/1055](url)
