### ISSUE TITLE
No matching version found for pawjs@^0.5.0

### ISSUE THREAD

**Issue by szhielelp** [Atyantik/react-pwa#92]
Hi, getting an issue when init installing in Win10 64b 1709

Here is the error msg:

> G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux>npm install
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\duplexify-7df183cc\package.json'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\duplexify-7df183cc\.travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\duplexify-7df183cc\example.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\duplexify-7df183cc\index.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\postcss-svgo-0ec09c1e\dist\index.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\whet.extend-69e21149\test\extend_test.coffee'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\babel-plugin-lodash-d97964ac\lib\config.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\duplexify-7df183cc\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\babel-plugin-lodash-d97964ac\lib\importModule.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\duplexify-7df183cc\README.md'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\whet.extend-69e21149\test\mocha.opts'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\babel-plugin-lodash-d97964ac\lib\index.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\stream-http-75eb7665\test\server\index.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\whet.extend-69e21149\test\test_helper.coffee'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\duplexify-7df183cc\test.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\whet.extend-69e21149\.travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\babel-plugin-lodash-d97964ac\lib\Map.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\whet.extend-69e21149\Cakefile'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\babel-plugin-lodash-d97964ac\lib\MapCache.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\node-sass-4d7b234f\src\libsass\contrib\libsass.spec'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\whet.extend-69e21149\History.md'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\whet.extend-69e21149\Readme.md'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\babel-plugin-lodash-d97964ac\lib\mapping.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\shelljs-6216fc15\bin\shjs'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\node-sass-4d7b234f\src\libsass\contrib\plugin.cpp'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\babel-plugin-lodash-d97964ac\lib\ModuleCache.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\core.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\babel-plugin-lodash-d97964ac\lib\Package.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\functionOptimiser.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\babel-plugin-lodash-d97964ac\lib\Store.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\getArguments.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\babel-plugin-lodash-d97964ac\lib\util.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\getMatch.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\jsdom-43ea0c18\lib\jsdom\browser\default-stylesheet.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\filterOptimiser.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\normalizeUnicode.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\reduceBackgroundRepeat.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\reduceDisplayValues.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\reducePositions.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\reduceTimingFunctions.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\evenValues.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\styleCache.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\cssnano-4372c7af\dist\lib\normalizeString.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\postcss-svgo-0ec09c1e\dist\lib\url.js'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\node-gyp-28d9c704\gyp\pylib\gyp\generator\gypsh.py'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\node-gyp-28d9c704\gyp\pylib\gyp\generator\__init__.py'
npm WARN tar ENOENT: no such file or directory, open 'G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux\node_modules\.staging\node-gyp-28d9c704\gyp\pylib\gyp\generator\android.py'
npm WARN ReactPWA@0.3.0 No repository field.
npm ERR! code ETARGET
npm ERR! notarget **No matching version found for pawjs@0.5.0**
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'ReactPWA'
npm ERR! notarget
npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Tools_For_Work\NodeJS\node_cache\_logs\2018-05-15T15_38_28_578Z-debug.log

Tried to do single install for pawjs but also got an error:

> G:\Dev\GitRepos\Tmp\ReduxAcademy\ReduxAcademy\5PWAwithRedux>npm install pawjs
npm ERR! code ETARGET
npm ERR! notarget **No matching version found for pawjs@^0.5.0**
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Tools_For_Work\NodeJS\node_cache\_logs\2018-05-15T15_42_46_581Z-debug.log

**Comment by tirthbodawala** [comment]
@szhielelp  we are upgrading and re-organizing the versions. Please bear with us a little bit. approx 2 hours please
