### ISSUE TITLE
sw.js cache invalidation

### ISSUE THREAD

**Issue by istackservices** [Atyantik/react-pwa#94]
Hi,

Could we have sw.js or anything service-worker related NOT being cached on the express server level so wont need to mess with nginx/apache config.

Thank you!

**Comment by tirthbodawala** [comment]
@istackservices sw.js is not cached at all that is made sure by us:

```javascript
app.use(`${pawConfig.appRootUrl}/sw.js`, express.static(path.join(currentDir, "build", "sw.js"), {
  maxAge: 0,
  setHeaders: (res) => {
    res.set("Cache-Control", "no-cache");
  }
}));
```
