### ISSUE TITLE
CSS import problem, classes renamed

### ISSUE THREAD

**Issue by Stunext** [Atyantik/react-pwa#97]
I have a very annoying problem, I try to integrate Reactstrap and as the documentation says, the css of the bootstrap package must be imported from node_modules. When doing this, the application does not render any css tag so I imagine that webpack is configured to ignore the css files in the node_modules folder. For this reason, I create an assets folder and import the code in the following way from the "client.js" file.

`import" ./assets/styles/bootstrap.css ";`

In doing so, a css file is compiled and added to the head of the page but the styles do not work, all classes are renamed as follows

`.src-assets-styles-bootstrap__btn`

In this case the original class is ".btn"

**Comment by tirthbodawala** [comment]
Well I will need to check why the node_modules are not working, but for a short fix:
Please place the CSS that is not supposed to be named in the folder:

`src/resources/assets/styles/boostrap.css`

Any CSS from resources folder is not custom named and stays as it is.

and include it in `src/client.js` as below:

```javascript
import "./resources/assets/styles/bootstrap.css";
// ..other code
```

**Comment by tirthbodawala** [comment]
Re-opening as still need to check the node_modules 's Issue!

**Comment by tirthbodawala** [comment]
@Stunext Yes that was it’s sole purpose! I should better get it documented :) apologies.

**Comment by sinner** [comment]
I'm still having this problem!
