### ISSUE TITLE
Shouldn't it be "save" instead of "save-dev"?

### ISSUE THREAD

**Issue by ericp96** [Atyantik/react-pwa#98]
Looking at your examples for plugins:
https://www.reactpwa.com/docs/en/plugin-redux.html

I'm a little surprised by the use of `npm i --save-dev` instead of `npm i --save`.  It seems like these would be production dependencies of the application, no?

**Comment by tirthbodawala** [comment]
@ericp96: Well ReactPWA is designed in such a manner that it can output standalone JS files that do not need any `npm i` on production!
 
all you need to do is once you build it, just run with the normal node as `node dist/server.js` and it will start no need for dependencies, thus everything in dev-dependencies only!

Hope that makes sense!

**Comment by ericp96** [comment]
Thanks for the details as to why you suggestion `--save-dev`  I can understand why you would take that approach.

Looking at this from the context of deploying in a microservices environment.  Would it be appropriate to have these as dependencies to prevent from having to set the NODE_ENV to development when doing an npm install & npm build in a Dockerfile?

Just postulating what a Dockerfile might look like:
```
FROM node:alpine

ADD . /srv
WORKDIR /srv

RUN npm install
RUN npm build

ENTRYPOINT ['node', 'run', 'dist/index.js']
```

Does that seem reasonable?  Or would you suggest doing a separate build+deployment to a separate artifact repository and then a pull of the compiled application in the Dockerfile?

**Comment by tirthbodawala** [comment]
@ericp96 The whole idea behind doing standalone JavaScript files is to avoid the unnecessary npm dependency and installation. 

Let me try to explain how I would do it.
For running the app locally via docker I would do something like below:
**NOTE** this is not the perfect Dockerfile one would expect! it is just an example.

## Local Docker Image
===== Starting and developing application locally =======

`StartDockerfile`
```
FROM node:latest
WORKDIR /app
COPY . .
RUN npm install
VOLUME ["/app/src", "/app/dist", "/app/src/pawconfig.json"]
EXPOSE 3003
CMD [ "npm", "start" ]
```

And then run the build the local development image as below:
```
docker build -t react-pwa -f StartDockerfile .
```

Thus, would then start development with following `docker run`
```
docker run -v "$PWD/src:/app/src" -v "$PWD/pawconfig.json:/app/pawconfig.json" -p 127.0.0.1:3003:3003 --rm react-pwa
```

==== Building application locally ==== 
I would reuse the code above and change the command as below
```
docker run -v "$PWD/src:/app/src" -v "$PWD/dist:/app/dist" -v "$PWD/pawconfig.json:/app/pawconfig.json" -p 127.0.0.1:3003:3003 --rm react-pwa npm run build
```

## Creating Production Docker Image

Once you have the local docker image in place and would like to build a production image do as below:

`ProdDockerfile`
```
FROM node:latest
WORKDIR /app
COPY ./dist .
VOLUME ["/app"]
EXPOSE 3003
CMD [ "node", "server.js" ]
```

===== Building the prod image =====

The below will create a docker image react-pwa-prod
```
docker build -t react-pwa-prod -f ProdDockerfile .
```

To check the image created above you can execute the following command:
```
docker run -p 127.0.0.1:3003:3003 --rm react-pwa-prod
```

The above commands are not properly tested but should work in accordance to my knowledge!

Hope the above helps @ericp96
